// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: jobs_registry.proto

package jobs_registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_LOW      Severity = 1
	Severity_MEDIUM   Severity = 2
	Severity_HIGH     Severity = 3
	Severity_CRITICAL Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_registry_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_jobs_registry_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{0}
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_jobs_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Asset         *Asset                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Command       *string                `protobuf:"bytes,3,opt,name=command,proto3,oneof" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_jobs_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Job) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_jobs_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{2}
}

func (x *JobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JobResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Data          *UpdateResultDto       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultRequest) Reset() {
	*x = JobResultRequest{}
	mi := &file_jobs_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultRequest) ProtoMessage() {}

func (x *JobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultRequest.ProtoReflect.Descriptor instead.
func (*JobResultRequest) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{3}
}

func (x *JobResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobResultRequest) GetData() *UpdateResultDto {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateResultDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Data          *DataPayloadResult     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResultDto) Reset() {
	*x = UpdateResultDto{}
	mi := &file_jobs_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResultDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResultDto) ProtoMessage() {}

func (x *UpdateResultDto) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResultDto.ProtoReflect.Descriptor instead.
func (*UpdateResultDto) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResultDto) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateResultDto) GetData() *DataPayloadResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataPayloadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Raw   *string                `protobuf:"bytes,2,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DataPayloadResult_Assets
	//	*DataPayloadResult_HttpResponse
	//	*DataPayloadResult_Numbers
	//	*DataPayloadResult_Vulnerabilities
	//	*DataPayloadResult_AssetTags
	Payload       isDataPayloadResult_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPayloadResult) Reset() {
	*x = DataPayloadResult{}
	mi := &file_jobs_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPayloadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPayloadResult) ProtoMessage() {}

func (x *DataPayloadResult) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPayloadResult.ProtoReflect.Descriptor instead.
func (*DataPayloadResult) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{5}
}

func (x *DataPayloadResult) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *DataPayloadResult) GetRaw() string {
	if x != nil && x.Raw != nil {
		return *x.Raw
	}
	return ""
}

func (x *DataPayloadResult) GetPayload() isDataPayloadResult_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataPayloadResult) GetAssets() *AssetList {
	if x != nil {
		if x, ok := x.Payload.(*DataPayloadResult_Assets); ok {
			return x.Assets
		}
	}
	return nil
}

func (x *DataPayloadResult) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Payload.(*DataPayloadResult_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

func (x *DataPayloadResult) GetNumbers() *NumberList {
	if x != nil {
		if x, ok := x.Payload.(*DataPayloadResult_Numbers); ok {
			return x.Numbers
		}
	}
	return nil
}

func (x *DataPayloadResult) GetVulnerabilities() *VulnerabilityList {
	if x != nil {
		if x, ok := x.Payload.(*DataPayloadResult_Vulnerabilities); ok {
			return x.Vulnerabilities
		}
	}
	return nil
}

func (x *DataPayloadResult) GetAssetTags() *AssetTagList {
	if x != nil {
		if x, ok := x.Payload.(*DataPayloadResult_AssetTags); ok {
			return x.AssetTags
		}
	}
	return nil
}

type isDataPayloadResult_Payload interface {
	isDataPayloadResult_Payload()
}

type DataPayloadResult_Assets struct {
	Assets *AssetList `protobuf:"bytes,3,opt,name=assets,proto3,oneof"`
}

type DataPayloadResult_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,4,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

type DataPayloadResult_Numbers struct {
	Numbers *NumberList `protobuf:"bytes,5,opt,name=numbers,proto3,oneof"`
}

type DataPayloadResult_Vulnerabilities struct {
	Vulnerabilities *VulnerabilityList `protobuf:"bytes,6,opt,name=vulnerabilities,proto3,oneof"`
}

type DataPayloadResult_AssetTags struct {
	AssetTags *AssetTagList `protobuf:"bytes,7,opt,name=asset_tags,json=assetTags,proto3,oneof"`
}

func (*DataPayloadResult_Assets) isDataPayloadResult_Payload() {}

func (*DataPayloadResult_HttpResponse) isDataPayloadResult_Payload() {}

func (*DataPayloadResult_Numbers) isDataPayloadResult_Payload() {}

func (*DataPayloadResult_Vulnerabilities) isDataPayloadResult_Payload() {}

func (*DataPayloadResult_AssetTags) isDataPayloadResult_Payload() {}

type AssetList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Asset               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetList) Reset() {
	*x = AssetList{}
	mi := &file_jobs_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetList) ProtoMessage() {}

func (x *AssetList) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetList.ProtoReflect.Descriptor instead.
func (*AssetList) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{6}
}

func (x *AssetList) GetValues() []*Asset {
	if x != nil {
		return x.Values
	}
	return nil
}

type NumberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberList) Reset() {
	*x = NumberList{}
	mi := &file_jobs_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberList) ProtoMessage() {}

func (x *NumberList) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberList.ProtoReflect.Descriptor instead.
func (*NumberList) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{7}
}

func (x *NumberList) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type VulnerabilityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Vulnerability       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VulnerabilityList) Reset() {
	*x = VulnerabilityList{}
	mi := &file_jobs_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VulnerabilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityList) ProtoMessage() {}

func (x *VulnerabilityList) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityList.ProtoReflect.Descriptor instead.
func (*VulnerabilityList) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{8}
}

func (x *VulnerabilityList) GetValues() []*Vulnerability {
	if x != nil {
		return x.Values
	}
	return nil
}

type AssetTagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AssetTag            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetTagList) Reset() {
	*x = AssetTagList{}
	mi := &file_jobs_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTagList) ProtoMessage() {}

func (x *AssetTagList) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTagList.ProtoReflect.Descriptor instead.
func (*AssetTagList) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{9}
}

func (x *AssetTagList) GetValues() []*AssetTag {
	if x != nil {
		return x.Values
	}
	return nil
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	TargetId      string                 `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,6,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	DnsRecords    *structpb.Struct       `protobuf:"bytes,7,opt,name=dns_records,json=dnsRecords,proto3" json:"dns_records,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,8,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_jobs_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{10}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Asset) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Asset) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Asset) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Asset) GetDnsRecords() *structpb.Struct {
	if x != nil {
		return x.DnsRecords
	}
	return nil
}

func (x *Asset) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type HttpResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tls              *structpb.Struct       `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	Port             string                 `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	Url              string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Input            string                 `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Title            string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Scheme           string                 `protobuf:"bytes,9,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Webserver        string                 `protobuf:"bytes,10,opt,name=webserver,proto3" json:"webserver,omitempty"`
	Body             string                 `protobuf:"bytes,11,opt,name=body,proto3" json:"body,omitempty"`
	ContentType      string                 `protobuf:"bytes,12,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Method           string                 `protobuf:"bytes,13,opt,name=method,proto3" json:"method,omitempty"`
	Host             string                 `protobuf:"bytes,14,opt,name=host,proto3" json:"host,omitempty"`
	Path             string                 `protobuf:"bytes,15,opt,name=path,proto3" json:"path,omitempty"`
	Favicon          string                 `protobuf:"bytes,16,opt,name=favicon,proto3" json:"favicon,omitempty"`
	FaviconMd5       string                 `protobuf:"bytes,17,opt,name=favicon_md5,json=faviconMd5,proto3" json:"favicon_md5,omitempty"`
	FaviconUrl       string                 `protobuf:"bytes,18,opt,name=favicon_url,json=faviconUrl,proto3" json:"favicon_url,omitempty"`
	Header           *structpb.Struct       `protobuf:"bytes,19,opt,name=header,proto3" json:"header,omitempty"` // jsonb
	RawHeader        string                 `protobuf:"bytes,20,opt,name=raw_header,json=rawHeader,proto3" json:"raw_header,omitempty"`
	Request          string                 `protobuf:"bytes,21,opt,name=request,proto3" json:"request,omitempty"`
	Time             string                 `protobuf:"bytes,22,opt,name=time,proto3" json:"time,omitempty"`
	A                []string               `protobuf:"bytes,23,rep,name=a,proto3" json:"a,omitempty"`
	Tech             []string               `protobuf:"bytes,24,rep,name=tech,proto3" json:"tech,omitempty"`
	Words            int32                  `protobuf:"varint,25,opt,name=words,proto3" json:"words,omitempty"`
	Lines            int32                  `protobuf:"varint,26,opt,name=lines,proto3" json:"lines,omitempty"`
	StatusCode       int32                  `protobuf:"varint,27,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ContentLength    int32                  `protobuf:"varint,28,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Failed           bool                   `protobuf:"varint,29,opt,name=failed,proto3" json:"failed,omitempty"`
	Knowledgebase    *structpb.Struct       `protobuf:"bytes,30,opt,name=knowledgebase,proto3" json:"knowledgebase,omitempty"` // jsonb
	Resolvers        []string               `protobuf:"bytes,31,rep,name=resolvers,proto3" json:"resolvers,omitempty"`
	ChainStatusCodes []string               `protobuf:"bytes,32,rep,name=chain_status_codes,json=chainStatusCodes,proto3" json:"chain_status_codes,omitempty"`
	AssetServiceId   string                 `protobuf:"bytes,33,opt,name=asset_service_id,json=assetServiceId,proto3" json:"asset_service_id,omitempty"`
	JobHistoryId     string                 `protobuf:"bytes,34,opt,name=job_history_id,json=jobHistoryId,proto3" json:"job_history_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_jobs_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{11}
}

func (x *HttpResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HttpResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HttpResponse) GetTls() *structpb.Struct {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *HttpResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *HttpResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpResponse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *HttpResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HttpResponse) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HttpResponse) GetWebserver() string {
	if x != nil {
		return x.Webserver
	}
	return ""
}

func (x *HttpResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HttpResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *HttpResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpResponse) GetFavicon() string {
	if x != nil {
		return x.Favicon
	}
	return ""
}

func (x *HttpResponse) GetFaviconMd5() string {
	if x != nil {
		return x.FaviconMd5
	}
	return ""
}

func (x *HttpResponse) GetFaviconUrl() string {
	if x != nil {
		return x.FaviconUrl
	}
	return ""
}

func (x *HttpResponse) GetHeader() *structpb.Struct {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HttpResponse) GetRawHeader() string {
	if x != nil {
		return x.RawHeader
	}
	return ""
}

func (x *HttpResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *HttpResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *HttpResponse) GetA() []string {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *HttpResponse) GetTech() []string {
	if x != nil {
		return x.Tech
	}
	return nil
}

func (x *HttpResponse) GetWords() int32 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *HttpResponse) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetContentLength() int32 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *HttpResponse) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *HttpResponse) GetKnowledgebase() *structpb.Struct {
	if x != nil {
		return x.Knowledgebase
	}
	return nil
}

func (x *HttpResponse) GetResolvers() []string {
	if x != nil {
		return x.Resolvers
	}
	return nil
}

func (x *HttpResponse) GetChainStatusCodes() []string {
	if x != nil {
		return x.ChainStatusCodes
	}
	return nil
}

func (x *HttpResponse) GetAssetServiceId() string {
	if x != nil {
		return x.AssetServiceId
	}
	return ""
}

func (x *HttpResponse) GetJobHistoryId() string {
	if x != nil {
		return x.JobHistoryId
	}
	return ""
}

type Vulnerability struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Synopsis         string                 `protobuf:"bytes,4,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Severity         Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=jobs_registry.Severity" json:"severity,omitempty"`
	Tags             []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	References       []string               `protobuf:"bytes,7,rep,name=references,proto3" json:"references,omitempty"`
	Authors          []string               `protobuf:"bytes,8,rep,name=authors,proto3" json:"authors,omitempty"`
	AffectedUrl      string                 `protobuf:"bytes,9,opt,name=affected_url,json=affectedUrl,proto3" json:"affected_url,omitempty"`
	IpAddress        string                 `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Host             string                 `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	Ports            []string               `protobuf:"bytes,12,rep,name=ports,proto3" json:"ports,omitempty"`
	CvssMetric       string                 `protobuf:"bytes,13,opt,name=cvss_metric,json=cvssMetric,proto3" json:"cvss_metric,omitempty"`
	CvssScore        float32                `protobuf:"fixed32,14,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	EpssScore        float32                `protobuf:"fixed32,15,opt,name=epss_score,json=epssScore,proto3" json:"epss_score,omitempty"`
	VprScore         float32                `protobuf:"fixed32,16,opt,name=vpr_score,json=vprScore,proto3" json:"vpr_score,omitempty"`
	CveId            []string               `protobuf:"bytes,17,rep,name=cve_id,json=cveId,proto3" json:"cve_id,omitempty"`
	BidId            []string               `protobuf:"bytes,18,rep,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	CweId            []string               `protobuf:"bytes,19,rep,name=cwe_id,json=cweId,proto3" json:"cwe_id,omitempty"`
	CeaId            []string               `protobuf:"bytes,20,rep,name=cea_id,json=ceaId,proto3" json:"cea_id,omitempty"`
	Iava             []string               `protobuf:"bytes,21,rep,name=iava,proto3" json:"iava,omitempty"`
	CveUrl           string                 `protobuf:"bytes,22,opt,name=cve_url,json=cveUrl,proto3" json:"cve_url,omitempty"`
	CweUrl           string                 `protobuf:"bytes,23,opt,name=cwe_url,json=cweUrl,proto3" json:"cwe_url,omitempty"`
	Solution         string                 `protobuf:"bytes,24,opt,name=solution,proto3" json:"solution,omitempty"`
	ExtractorName    string                 `protobuf:"bytes,25,opt,name=extractor_name,json=extractorName,proto3" json:"extractor_name,omitempty"`
	ExtractedResults []string               `protobuf:"bytes,26,rep,name=extracted_results,json=extractedResults,proto3" json:"extracted_results,omitempty"`
	PublicationDate  *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=publication_date,json=publicationDate,proto3" json:"publication_date,omitempty"`
	ModificationDate *timestamppb.Timestamp `protobuf:"bytes,28,opt,name=modification_date,json=modificationDate,proto3" json:"modification_date,omitempty"`
	ToolId           string                 `protobuf:"bytes,29,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`    // Relation ID
	AssetId          string                 `protobuf:"bytes,30,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"` // Relation ID
	FilePath         string                 `protobuf:"bytes,31,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	JobHistoryId     string                 `protobuf:"bytes,32,opt,name=job_history_id,json=jobHistoryId,proto3" json:"job_history_id,omitempty"`
	IsArchived       bool                   `protobuf:"varint,33,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	Fingerprint      string                 `protobuf:"bytes,34,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_jobs_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vulnerability.ProtoReflect.Descriptor instead.
func (*Vulnerability) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{12}
}

func (x *Vulnerability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vulnerability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vulnerability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vulnerability) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Vulnerability) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

func (x *Vulnerability) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Vulnerability) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *Vulnerability) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Vulnerability) GetAffectedUrl() string {
	if x != nil {
		return x.AffectedUrl
	}
	return ""
}

func (x *Vulnerability) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Vulnerability) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Vulnerability) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Vulnerability) GetCvssMetric() string {
	if x != nil {
		return x.CvssMetric
	}
	return ""
}

func (x *Vulnerability) GetCvssScore() float32 {
	if x != nil {
		return x.CvssScore
	}
	return 0
}

func (x *Vulnerability) GetEpssScore() float32 {
	if x != nil {
		return x.EpssScore
	}
	return 0
}

func (x *Vulnerability) GetVprScore() float32 {
	if x != nil {
		return x.VprScore
	}
	return 0
}

func (x *Vulnerability) GetCveId() []string {
	if x != nil {
		return x.CveId
	}
	return nil
}

func (x *Vulnerability) GetBidId() []string {
	if x != nil {
		return x.BidId
	}
	return nil
}

func (x *Vulnerability) GetCweId() []string {
	if x != nil {
		return x.CweId
	}
	return nil
}

func (x *Vulnerability) GetCeaId() []string {
	if x != nil {
		return x.CeaId
	}
	return nil
}

func (x *Vulnerability) GetIava() []string {
	if x != nil {
		return x.Iava
	}
	return nil
}

func (x *Vulnerability) GetCveUrl() string {
	if x != nil {
		return x.CveUrl
	}
	return ""
}

func (x *Vulnerability) GetCweUrl() string {
	if x != nil {
		return x.CweUrl
	}
	return ""
}

func (x *Vulnerability) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *Vulnerability) GetExtractorName() string {
	if x != nil {
		return x.ExtractorName
	}
	return ""
}

func (x *Vulnerability) GetExtractedResults() []string {
	if x != nil {
		return x.ExtractedResults
	}
	return nil
}

func (x *Vulnerability) GetPublicationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PublicationDate
	}
	return nil
}

func (x *Vulnerability) GetModificationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ModificationDate
	}
	return nil
}

func (x *Vulnerability) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *Vulnerability) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Vulnerability) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Vulnerability) GetJobHistoryId() string {
	if x != nil {
		return x.JobHistoryId
	}
	return ""
}

func (x *Vulnerability) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Vulnerability) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type AssetTag struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag            string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	AssetServiceId string                 `protobuf:"bytes,3,opt,name=asset_service_id,json=assetServiceId,proto3" json:"asset_service_id,omitempty"`
	ToolId         string                 `protobuf:"bytes,4,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetTag) Reset() {
	*x = AssetTag{}
	mi := &file_jobs_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTag) ProtoMessage() {}

func (x *AssetTag) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTag.ProtoReflect.Descriptor instead.
func (*AssetTag) Descriptor() ([]byte, []int) {
	return file_jobs_registry_proto_rawDescGZIP(), []int{13}
}

func (x *AssetTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssetTag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AssetTag) GetAssetServiceId() string {
	if x != nil {
		return x.AssetServiceId
	}
	return ""
}

func (x *AssetTag) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

var File_jobs_registry_proto protoreflect.FileDescriptor

const file_jobs_registry_proto_rawDesc = "" +
	"\n" +
	"\x13jobs_registry.proto\x12\rjobs_registry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x18\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x05asset\x18\x02 \x01(\v2\x14.jobs_registry.AssetR\x05asset\x12\x1d\n" +
	"\acommand\x18\x03 \x01(\tH\x00R\acommand\x88\x01\x01B\n" +
	"\n" +
	"\b_command\"'\n" +
	"\vJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x10JobResultRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.jobs_registry.UpdateResultDtoR\x04data\"^\n" +
	"\x0fUpdateResultDto\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x124\n" +
	"\x04data\x18\x02 \x01(\v2 .jobs_registry.DataPayloadResultR\x04data\"\x8e\x03\n" +
	"\x11DataPayloadResult\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error\x12\x15\n" +
	"\x03raw\x18\x02 \x01(\tH\x01R\x03raw\x88\x01\x01\x122\n" +
	"\x06assets\x18\x03 \x01(\v2\x18.jobs_registry.AssetListH\x00R\x06assets\x12B\n" +
	"\rhttp_response\x18\x04 \x01(\v2\x1b.jobs_registry.HttpResponseH\x00R\fhttpResponse\x125\n" +
	"\anumbers\x18\x05 \x01(\v2\x19.jobs_registry.NumberListH\x00R\anumbers\x12L\n" +
	"\x0fvulnerabilities\x18\x06 \x01(\v2 .jobs_registry.VulnerabilityListH\x00R\x0fvulnerabilities\x12<\n" +
	"\n" +
	"asset_tags\x18\a \x01(\v2\x1b.jobs_registry.AssetTagListH\x00R\tassetTagsB\t\n" +
	"\apayloadB\x06\n" +
	"\x04_raw\"9\n" +
	"\tAssetList\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.jobs_registry.AssetR\x06values\"$\n" +
	"\n" +
	"NumberList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"I\n" +
	"\x11VulnerabilityList\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.jobs_registry.VulnerabilityR\x06values\"?\n" +
	"\fAssetTagList\x12/\n" +
	"\x06values\x18\x01 \x03(\v2\x17.jobs_registry.AssetTagR\x06values\"\xb8\x02\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x06 \x01(\bR\tisPrimary\x128\n" +
	"\vdns_records\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"dnsRecords\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\b \x01(\bR\tisEnabled\"\xa0\b\n" +
	"\fHttpResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x03tls\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x03tls\x12\x12\n" +
	"\x04port\x18\x05 \x01(\tR\x04port\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x14\n" +
	"\x05input\x18\a \x01(\tR\x05input\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x16\n" +
	"\x06scheme\x18\t \x01(\tR\x06scheme\x12\x1c\n" +
	"\twebserver\x18\n" +
	" \x01(\tR\twebserver\x12\x12\n" +
	"\x04body\x18\v \x01(\tR\x04body\x12!\n" +
	"\fcontent_type\x18\f \x01(\tR\vcontentType\x12\x16\n" +
	"\x06method\x18\r \x01(\tR\x06method\x12\x12\n" +
	"\x04host\x18\x0e \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x0f \x01(\tR\x04path\x12\x18\n" +
	"\afavicon\x18\x10 \x01(\tR\afavicon\x12\x1f\n" +
	"\vfavicon_md5\x18\x11 \x01(\tR\n" +
	"faviconMd5\x12\x1f\n" +
	"\vfavicon_url\x18\x12 \x01(\tR\n" +
	"faviconUrl\x12/\n" +
	"\x06header\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x06header\x12\x1d\n" +
	"\n" +
	"raw_header\x18\x14 \x01(\tR\trawHeader\x12\x18\n" +
	"\arequest\x18\x15 \x01(\tR\arequest\x12\x12\n" +
	"\x04time\x18\x16 \x01(\tR\x04time\x12\f\n" +
	"\x01a\x18\x17 \x03(\tR\x01a\x12\x12\n" +
	"\x04tech\x18\x18 \x03(\tR\x04tech\x12\x14\n" +
	"\x05words\x18\x19 \x01(\x05R\x05words\x12\x14\n" +
	"\x05lines\x18\x1a \x01(\x05R\x05lines\x12\x1f\n" +
	"\vstatus_code\x18\x1b \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0econtent_length\x18\x1c \x01(\x05R\rcontentLength\x12\x16\n" +
	"\x06failed\x18\x1d \x01(\bR\x06failed\x12=\n" +
	"\rknowledgebase\x18\x1e \x01(\v2\x17.google.protobuf.StructR\rknowledgebase\x12\x1c\n" +
	"\tresolvers\x18\x1f \x03(\tR\tresolvers\x12,\n" +
	"\x12chain_status_codes\x18  \x03(\tR\x10chainStatusCodes\x12(\n" +
	"\x10asset_service_id\x18! \x01(\tR\x0eassetServiceId\x12$\n" +
	"\x0ejob_history_id\x18\" \x01(\tR\fjobHistoryId\"\xb8\b\n" +
	"\rVulnerability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsynopsis\x18\x04 \x01(\tR\bsynopsis\x123\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x17.jobs_registry.SeverityR\bseverity\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"references\x18\a \x03(\tR\n" +
	"references\x12\x18\n" +
	"\aauthors\x18\b \x03(\tR\aauthors\x12!\n" +
	"\faffected_url\x18\t \x01(\tR\vaffectedUrl\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12\x14\n" +
	"\x05ports\x18\f \x03(\tR\x05ports\x12\x1f\n" +
	"\vcvss_metric\x18\r \x01(\tR\n" +
	"cvssMetric\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\x0e \x01(\x02R\tcvssScore\x12\x1d\n" +
	"\n" +
	"epss_score\x18\x0f \x01(\x02R\tepssScore\x12\x1b\n" +
	"\tvpr_score\x18\x10 \x01(\x02R\bvprScore\x12\x15\n" +
	"\x06cve_id\x18\x11 \x03(\tR\x05cveId\x12\x15\n" +
	"\x06bid_id\x18\x12 \x03(\tR\x05bidId\x12\x15\n" +
	"\x06cwe_id\x18\x13 \x03(\tR\x05cweId\x12\x15\n" +
	"\x06cea_id\x18\x14 \x03(\tR\x05ceaId\x12\x12\n" +
	"\x04iava\x18\x15 \x03(\tR\x04iava\x12\x17\n" +
	"\acve_url\x18\x16 \x01(\tR\x06cveUrl\x12\x17\n" +
	"\acwe_url\x18\x17 \x01(\tR\x06cweUrl\x12\x1a\n" +
	"\bsolution\x18\x18 \x01(\tR\bsolution\x12%\n" +
	"\x0eextractor_name\x18\x19 \x01(\tR\rextractorName\x12+\n" +
	"\x11extracted_results\x18\x1a \x03(\tR\x10extractedResults\x12E\n" +
	"\x10publication_date\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\x0fpublicationDate\x12G\n" +
	"\x11modification_date\x18\x1c \x01(\v2\x1a.google.protobuf.TimestampR\x10modificationDate\x12\x17\n" +
	"\atool_id\x18\x1d \x01(\tR\x06toolId\x12\x19\n" +
	"\basset_id\x18\x1e \x01(\tR\aassetId\x12\x1b\n" +
	"\tfile_path\x18\x1f \x01(\tR\bfilePath\x12$\n" +
	"\x0ejob_history_id\x18  \x01(\tR\fjobHistoryId\x12\x1f\n" +
	"\vis_archived\x18! \x01(\bR\n" +
	"isArchived\x12 \n" +
	"\vfingerprint\x18\" \x01(\tR\vfingerprint\"o\n" +
	"\bAssetTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12(\n" +
	"\x10asset_service_id\x18\x03 \x01(\tR\x0eassetServiceId\x12\x17\n" +
	"\atool_id\x18\x04 \x01(\tR\x06toolId*A\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\x8f\x01\n" +
	"\x13JobsRegistryService\x121\n" +
	"\x04Next\x12\x15.jobs_registry.Worker\x1a\x12.jobs_registry.Job\x12E\n" +
	"\x06Result\x12\x1f.jobs_registry.JobResultRequest\x1a\x1a.jobs_registry.JobResponseB\x11Z\x0f./jobs_registryb\x06proto3"

var (
	file_jobs_registry_proto_rawDescOnce sync.Once
	file_jobs_registry_proto_rawDescData []byte
)

func file_jobs_registry_proto_rawDescGZIP() []byte {
	file_jobs_registry_proto_rawDescOnce.Do(func() {
		file_jobs_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_registry_proto_rawDesc), len(file_jobs_registry_proto_rawDesc)))
	})
	return file_jobs_registry_proto_rawDescData
}

var file_jobs_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobs_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_jobs_registry_proto_goTypes = []any{
	(Severity)(0),                 // 0: jobs_registry.Severity
	(*Worker)(nil),                // 1: jobs_registry.Worker
	(*Job)(nil),                   // 2: jobs_registry.Job
	(*JobResponse)(nil),           // 3: jobs_registry.JobResponse
	(*JobResultRequest)(nil),      // 4: jobs_registry.JobResultRequest
	(*UpdateResultDto)(nil),       // 5: jobs_registry.UpdateResultDto
	(*DataPayloadResult)(nil),     // 6: jobs_registry.DataPayloadResult
	(*AssetList)(nil),             // 7: jobs_registry.AssetList
	(*NumberList)(nil),            // 8: jobs_registry.NumberList
	(*VulnerabilityList)(nil),     // 9: jobs_registry.VulnerabilityList
	(*AssetTagList)(nil),          // 10: jobs_registry.AssetTagList
	(*Asset)(nil),                 // 11: jobs_registry.Asset
	(*HttpResponse)(nil),          // 12: jobs_registry.HttpResponse
	(*Vulnerability)(nil),         // 13: jobs_registry.Vulnerability
	(*AssetTag)(nil),              // 14: jobs_registry.AssetTag
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 16: google.protobuf.Struct
}
var file_jobs_registry_proto_depIdxs = []int32{
	11, // 0: jobs_registry.Job.asset:type_name -> jobs_registry.Asset
	5,  // 1: jobs_registry.JobResultRequest.data:type_name -> jobs_registry.UpdateResultDto
	6,  // 2: jobs_registry.UpdateResultDto.data:type_name -> jobs_registry.DataPayloadResult
	7,  // 3: jobs_registry.DataPayloadResult.assets:type_name -> jobs_registry.AssetList
	12, // 4: jobs_registry.DataPayloadResult.http_response:type_name -> jobs_registry.HttpResponse
	8,  // 5: jobs_registry.DataPayloadResult.numbers:type_name -> jobs_registry.NumberList
	9,  // 6: jobs_registry.DataPayloadResult.vulnerabilities:type_name -> jobs_registry.VulnerabilityList
	10, // 7: jobs_registry.DataPayloadResult.asset_tags:type_name -> jobs_registry.AssetTagList
	11, // 8: jobs_registry.AssetList.values:type_name -> jobs_registry.Asset
	13, // 9: jobs_registry.VulnerabilityList.values:type_name -> jobs_registry.Vulnerability
	14, // 10: jobs_registry.AssetTagList.values:type_name -> jobs_registry.AssetTag
	15, // 11: jobs_registry.Asset.created_at:type_name -> google.protobuf.Timestamp
	15, // 12: jobs_registry.Asset.updated_at:type_name -> google.protobuf.Timestamp
	16, // 13: jobs_registry.Asset.dns_records:type_name -> google.protobuf.Struct
	15, // 14: jobs_registry.HttpResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 15: jobs_registry.HttpResponse.timestamp:type_name -> google.protobuf.Timestamp
	16, // 16: jobs_registry.HttpResponse.tls:type_name -> google.protobuf.Struct
	16, // 17: jobs_registry.HttpResponse.header:type_name -> google.protobuf.Struct
	16, // 18: jobs_registry.HttpResponse.knowledgebase:type_name -> google.protobuf.Struct
	0,  // 19: jobs_registry.Vulnerability.severity:type_name -> jobs_registry.Severity
	15, // 20: jobs_registry.Vulnerability.publication_date:type_name -> google.protobuf.Timestamp
	15, // 21: jobs_registry.Vulnerability.modification_date:type_name -> google.protobuf.Timestamp
	1,  // 22: jobs_registry.JobsRegistryService.Next:input_type -> jobs_registry.Worker
	4,  // 23: jobs_registry.JobsRegistryService.Result:input_type -> jobs_registry.JobResultRequest
	2,  // 24: jobs_registry.JobsRegistryService.Next:output_type -> jobs_registry.Job
	3,  // 25: jobs_registry.JobsRegistryService.Result:output_type -> jobs_registry.JobResponse
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_jobs_registry_proto_init() }
func file_jobs_registry_proto_init() {
	if File_jobs_registry_proto != nil {
		return
	}
	file_jobs_registry_proto_msgTypes[1].OneofWrappers = []any{}
	file_jobs_registry_proto_msgTypes[5].OneofWrappers = []any{
		(*DataPayloadResult_Assets)(nil),
		(*DataPayloadResult_HttpResponse)(nil),
		(*DataPayloadResult_Numbers)(nil),
		(*DataPayloadResult_Vulnerabilities)(nil),
		(*DataPayloadResult_AssetTags)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_registry_proto_rawDesc), len(file_jobs_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobs_registry_proto_goTypes,
		DependencyIndexes: file_jobs_registry_proto_depIdxs,
		EnumInfos:         file_jobs_registry_proto_enumTypes,
		MessageInfos:      file_jobs_registry_proto_msgTypes,
	}.Build()
	File_jobs_registry_proto = out.File
	file_jobs_registry_proto_goTypes = nil
	file_jobs_registry_proto_depIdxs = nil
}
