// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: jobs_registry.proto

package jobs_registry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobsRegistryService_Next_FullMethodName   = "/jobs_registry.JobsRegistryService/Next"
	JobsRegistryService_Result_FullMethodName = "/jobs_registry.JobsRegistryService/Result"
)

// JobsRegistryServiceClient is the client API for JobsRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Definition
type JobsRegistryServiceClient interface {
	Next(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Job, error)
	Result(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type jobsRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobsRegistryServiceClient(cc grpc.ClientConnInterface) JobsRegistryServiceClient {
	return &jobsRegistryServiceClient{cc}
}

func (c *jobsRegistryServiceClient) Next(ctx context.Context, in *Worker, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, JobsRegistryService_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsRegistryServiceClient) Result(ctx context.Context, in *JobResultRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, JobsRegistryService_Result_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobsRegistryServiceServer is the server API for JobsRegistryService service.
// All implementations must embed UnimplementedJobsRegistryServiceServer
// for forward compatibility.
//
// Service Definition
type JobsRegistryServiceServer interface {
	Next(context.Context, *Worker) (*Job, error)
	Result(context.Context, *JobResultRequest) (*JobResponse, error)
	mustEmbedUnimplementedJobsRegistryServiceServer()
}

// UnimplementedJobsRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobsRegistryServiceServer struct{}

func (UnimplementedJobsRegistryServiceServer) Next(context.Context, *Worker) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedJobsRegistryServiceServer) Result(context.Context, *JobResultRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Result not implemented")
}
func (UnimplementedJobsRegistryServiceServer) mustEmbedUnimplementedJobsRegistryServiceServer() {}
func (UnimplementedJobsRegistryServiceServer) testEmbeddedByValue()                             {}

// UnsafeJobsRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobsRegistryServiceServer will
// result in compilation errors.
type UnsafeJobsRegistryServiceServer interface {
	mustEmbedUnimplementedJobsRegistryServiceServer()
}

func RegisterJobsRegistryServiceServer(s grpc.ServiceRegistrar, srv JobsRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedJobsRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobsRegistryService_ServiceDesc, srv)
}

func _JobsRegistryService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Worker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).Next(ctx, req.(*Worker))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsRegistryService_Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsRegistryServiceServer).Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsRegistryService_Result_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsRegistryServiceServer).Result(ctx, req.(*JobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobsRegistryService_ServiceDesc is the grpc.ServiceDesc for JobsRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobsRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobs_registry.JobsRegistryService",
	HandlerType: (*JobsRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _JobsRegistryService_Next_Handler,
		},
		{
			MethodName: "Result",
			Handler:    _JobsRegistryService_Result_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobs_registry.proto",
}
