// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: workers.proto

package workers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteExecuteSubscribeEventType int32

const (
	RemoteExecuteSubscribeEventType_REMOTE_EXECUTE_SUBSCRIBE_EVENT_UNKNOWN   RemoteExecuteSubscribeEventType = 0
	RemoteExecuteSubscribeEventType_REMOTE_EXECUTE_SUBSCRIBE_EVENT_CONNECTED RemoteExecuteSubscribeEventType = 1
	RemoteExecuteSubscribeEventType_REMOTE_EXECUTE_SUBSCRIBE_EVENT_COMMAND   RemoteExecuteSubscribeEventType = 2
)

// Enum value maps for RemoteExecuteSubscribeEventType.
var (
	RemoteExecuteSubscribeEventType_name = map[int32]string{
		0: "REMOTE_EXECUTE_SUBSCRIBE_EVENT_UNKNOWN",
		1: "REMOTE_EXECUTE_SUBSCRIBE_EVENT_CONNECTED",
		2: "REMOTE_EXECUTE_SUBSCRIBE_EVENT_COMMAND",
	}
	RemoteExecuteSubscribeEventType_value = map[string]int32{
		"REMOTE_EXECUTE_SUBSCRIBE_EVENT_UNKNOWN":   0,
		"REMOTE_EXECUTE_SUBSCRIBE_EVENT_CONNECTED": 1,
		"REMOTE_EXECUTE_SUBSCRIBE_EVENT_COMMAND":   2,
	}
)

func (x RemoteExecuteSubscribeEventType) Enum() *RemoteExecuteSubscribeEventType {
	p := new(RemoteExecuteSubscribeEventType)
	*p = x
	return p
}

func (x RemoteExecuteSubscribeEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteExecuteSubscribeEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_workers_proto_enumTypes[0].Descriptor()
}

func (RemoteExecuteSubscribeEventType) Type() protoreflect.EnumType {
	return &file_workers_proto_enumTypes[0]
}

func (x RemoteExecuteSubscribeEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteExecuteSubscribeEventType.Descriptor instead.
func (RemoteExecuteSubscribeEventType) EnumDescriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{0}
}

type RemoteExecuteResultEventType int32

const (
	RemoteExecuteResultEventType_REMOTE_EXECUTE_RESULT_UNKNOWN RemoteExecuteResultEventType = 0
	RemoteExecuteResultEventType_REMOTE_EXECUTE_RESULT_STDOUT  RemoteExecuteResultEventType = 1
	RemoteExecuteResultEventType_REMOTE_EXECUTE_RESULT_STDERR  RemoteExecuteResultEventType = 2
	RemoteExecuteResultEventType_REMOTE_EXECUTE_RESULT_EXIT    RemoteExecuteResultEventType = 3
	RemoteExecuteResultEventType_REMOTE_EXECUTE_RESULT_ERROR   RemoteExecuteResultEventType = 4
)

// Enum value maps for RemoteExecuteResultEventType.
var (
	RemoteExecuteResultEventType_name = map[int32]string{
		0: "REMOTE_EXECUTE_RESULT_UNKNOWN",
		1: "REMOTE_EXECUTE_RESULT_STDOUT",
		2: "REMOTE_EXECUTE_RESULT_STDERR",
		3: "REMOTE_EXECUTE_RESULT_EXIT",
		4: "REMOTE_EXECUTE_RESULT_ERROR",
	}
	RemoteExecuteResultEventType_value = map[string]int32{
		"REMOTE_EXECUTE_RESULT_UNKNOWN": 0,
		"REMOTE_EXECUTE_RESULT_STDOUT":  1,
		"REMOTE_EXECUTE_RESULT_STDERR":  2,
		"REMOTE_EXECUTE_RESULT_EXIT":    3,
		"REMOTE_EXECUTE_RESULT_ERROR":   4,
	}
)

func (x RemoteExecuteResultEventType) Enum() *RemoteExecuteResultEventType {
	p := new(RemoteExecuteResultEventType)
	*p = x
	return p
}

func (x RemoteExecuteResultEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteExecuteResultEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_workers_proto_enumTypes[1].Descriptor()
}

func (RemoteExecuteResultEventType) Type() protoreflect.EnumType {
	return &file_workers_proto_enumTypes[1]
}

func (x RemoteExecuteResultEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteExecuteResultEventType.Descriptor instead.
func (RemoteExecuteResultEventType) EnumDescriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{1}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Token         *string                `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Metadata      *WorkerMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_workers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *JoinRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *JoinRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *JoinRequest) GetMetadata() *WorkerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WorkerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Os            *string                `protobuf:"bytes,2,opt,name=os,proto3,oneof" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMetadata) Reset() {
	*x = WorkerMetadata{}
	mi := &file_workers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMetadata) ProtoMessage() {}

func (x *WorkerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMetadata.ProtoReflect.Descriptor instead.
func (*WorkerMetadata) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *WorkerMetadata) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerToken   string                 `protobuf:"bytes,2,opt,name=worker_token,json=workerToken,proto3" json:"worker_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_workers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JoinResponse) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerToken   string                 `protobuf:"bytes,1,opt,name=worker_token,json=workerToken,proto3" json:"worker_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveRequest) Reset() {
	*x = AliveRequest{}
	mi := &file_workers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveRequest) ProtoMessage() {}

func (x *AliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveRequest.ProtoReflect.Descriptor instead.
func (*AliveRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{3}
}

func (x *AliveRequest) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_workers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{4}
}

func (x *AliveResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *AliveResponse) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *AliveResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_workers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{5}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitCommands  []string               `protobuf:"bytes,1,rep,name=init_commands,json=initCommands,proto3" json:"init_commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_workers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{6}
}

func (x *GetManifestResponse) GetInitCommands() []string {
	if x != nil {
		return x.InitCommands
	}
	return nil
}

type StorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageRequest) Reset() {
	*x = StorageRequest{}
	mi := &file_workers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequest) ProtoMessage() {}

func (x *StorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequest.ProtoReflect.Descriptor instead.
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{7}
}

func (x *StorageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_workers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{8}
}

func (x *StorageResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *StorageResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StorageResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type NetworkInterfaceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Cidr          string                 `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayMac    string                 `protobuf:"bytes,5,opt,name=gateway_mac,json=gatewayMac,proto3" json:"gateway_mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterfaceMessage) Reset() {
	*x = NetworkInterfaceMessage{}
	mi := &file_workers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceMessage) ProtoMessage() {}

func (x *NetworkInterfaceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceMessage.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceMessage) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkInterfaceMessage) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetGatewayMac() string {
	if x != nil {
		return x.GatewayMac
	}
	return ""
}

type ConnectInternalNetworkRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	WorkerId          string                     `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	NetworkId         string                     `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NetworkInterfaces []*NetworkInterfaceMessage `protobuf:"bytes,3,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectInternalNetworkRequest) Reset() {
	*x = ConnectInternalNetworkRequest{}
	mi := &file_workers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectInternalNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInternalNetworkRequest) ProtoMessage() {}

func (x *ConnectInternalNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInternalNetworkRequest.ProtoReflect.Descriptor instead.
func (*ConnectInternalNetworkRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectInternalNetworkRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ConnectInternalNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ConnectInternalNetworkRequest) GetNetworkInterfaces() []*NetworkInterfaceMessage {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type ConnectInternalNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectInternalNetworkResponse) Reset() {
	*x = ConnectInternalNetworkResponse{}
	mi := &file_workers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectInternalNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInternalNetworkResponse) ProtoMessage() {}

func (x *ConnectInternalNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInternalNetworkResponse.ProtoReflect.Descriptor instead.
func (*ConnectInternalNetworkResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectInternalNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BuiltinToolRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`     // worker sends: runtime.GOOS (e.g., "linux")
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"` // worker sends: runtime.GOARCH (e.g., "arm64")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuiltinToolRegistryRequest) Reset() {
	*x = BuiltinToolRegistryRequest{}
	mi := &file_workers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuiltinToolRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltinToolRegistryRequest) ProtoMessage() {}

func (x *BuiltinToolRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltinToolRegistryRequest.ProtoReflect.Descriptor instead.
func (*BuiltinToolRegistryRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{12}
}

func (x *BuiltinToolRegistryRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *BuiltinToolRegistryRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type BuiltinToolRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolPaths     []string               `protobuf:"bytes,1,rep,name=tool_paths,json=toolPaths,proto3" json:"tool_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuiltinToolRegistryResponse) Reset() {
	*x = BuiltinToolRegistryResponse{}
	mi := &file_workers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuiltinToolRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltinToolRegistryResponse) ProtoMessage() {}

func (x *BuiltinToolRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltinToolRegistryResponse.ProtoReflect.Descriptor instead.
func (*BuiltinToolRegistryResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{13}
}

func (x *BuiltinToolRegistryResponse) GetToolPaths() []string {
	if x != nil {
		return x.ToolPaths
	}
	return nil
}

type RemoteExecuteSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteExecuteSubscribeRequest) Reset() {
	*x = RemoteExecuteSubscribeRequest{}
	mi := &file_workers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecuteSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecuteSubscribeRequest) ProtoMessage() {}

func (x *RemoteExecuteSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecuteSubscribeRequest.ProtoReflect.Descriptor instead.
func (*RemoteExecuteSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{14}
}

type RemoteExecuteSubscribeResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Id            string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkerId      string                          `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Type          RemoteExecuteSubscribeEventType `protobuf:"varint,3,opt,name=type,proto3,enum=workers.RemoteExecuteSubscribeEventType" json:"type,omitempty"`
	SessionId     string                          `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                          `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteExecuteSubscribeResponse) Reset() {
	*x = RemoteExecuteSubscribeResponse{}
	mi := &file_workers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecuteSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecuteSubscribeResponse) ProtoMessage() {}

func (x *RemoteExecuteSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecuteSubscribeResponse.ProtoReflect.Descriptor instead.
func (*RemoteExecuteSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{15}
}

func (x *RemoteExecuteSubscribeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoteExecuteSubscribeResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RemoteExecuteSubscribeResponse) GetType() RemoteExecuteSubscribeEventType {
	if x != nil {
		return x.Type
	}
	return RemoteExecuteSubscribeEventType_REMOTE_EXECUTE_SUBSCRIBE_EVENT_UNKNOWN
}

func (x *RemoteExecuteSubscribeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoteExecuteSubscribeResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RemoteExecuteResultStream struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                       `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          RemoteExecuteResultEventType `protobuf:"varint,3,opt,name=type,proto3,enum=workers.RemoteExecuteResultEventType" json:"type,omitempty"`
	Data          []byte                       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ExitCode      int32                        `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteExecuteResultStream) Reset() {
	*x = RemoteExecuteResultStream{}
	mi := &file_workers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecuteResultStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecuteResultStream) ProtoMessage() {}

func (x *RemoteExecuteResultStream) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecuteResultStream.ProtoReflect.Descriptor instead.
func (*RemoteExecuteResultStream) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{16}
}

func (x *RemoteExecuteResultStream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoteExecuteResultStream) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoteExecuteResultStream) GetType() RemoteExecuteResultEventType {
	if x != nil {
		return x.Type
	}
	return RemoteExecuteResultEventType_REMOTE_EXECUTE_RESULT_UNKNOWN
}

func (x *RemoteExecuteResultStream) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RemoteExecuteResultStream) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RemoteExecuteResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteExecuteResultAck) Reset() {
	*x = RemoteExecuteResultAck{}
	mi := &file_workers_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteExecuteResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteExecuteResultAck) ProtoMessage() {}

func (x *RemoteExecuteResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteExecuteResultAck.ProtoReflect.Descriptor instead.
func (*RemoteExecuteResultAck) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{17}
}

func (x *RemoteExecuteResultAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoteExecuteResultAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workers_proto protoreflect.FileDescriptor

const file_workers_proto_rawDesc = "" +
	"\n" +
	"\rworkers.proto\x12\aworkers\"\xb0\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x19\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x88\x01\x01\x128\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.workers.WorkerMetadataH\x01R\bmetadata\x88\x01\x01B\b\n" +
	"\x06_tokenB\v\n" +
	"\t_metadata\"N\n" +
	"\x0eWorkerMetadata\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\x02 \x01(\tH\x01R\x02os\x88\x01\x01B\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_os\"N\n" +
	"\fJoinResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fworker_token\x18\x02 \x01(\tR\vworkerToken\"1\n" +
	"\fAliveRequest\x12!\n" +
	"\fworker_token\x18\x01 \x01(\tR\vworkerToken\"d\n" +
	"\rAliveResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12 \n" +
	"\flast_seen_at\x18\x02 \x01(\tR\n" +
	"lastSeenAt\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\x14\n" +
	"\x12GetManifestRequest\":\n" +
	"\x13GetManifestResponse\x12#\n" +
	"\rinit_commands\x18\x01 \x03(\tR\finitCommands\"$\n" +
	"\x0eStorageRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Q\n" +
	"\x0fStorageResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"\xb3\x01\n" +
	"\x17NetworkInterfaceMessage\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04cidr\x18\x03 \x01(\tR\x04cidr\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x04 \x01(\tR\tgatewayIp\x12\x1f\n" +
	"\vgateway_mac\x18\x05 \x01(\tR\n" +
	"gatewayMac\"\xac\x01\n" +
	"\x1dConnectInternalNetworkRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12O\n" +
	"\x12network_interfaces\x18\x03 \x03(\v2 .workers.NetworkInterfaceMessageR\x11networkInterfaces\":\n" +
	"\x1eConnectInternalNetworkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x1aBuiltinToolRegistryRequest\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"<\n" +
	"\x1bBuiltinToolRegistryResponse\x12\x1d\n" +
	"\n" +
	"tool_paths\x18\x01 \x03(\tR\ttoolPaths\"\x1f\n" +
	"\x1dRemoteExecuteSubscribeRequest\"\xc4\x01\n" +
	"\x1eRemoteExecuteSubscribeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12<\n" +
	"\x04type\x18\x03 \x01(\x0e2(.workers.RemoteExecuteSubscribeEventTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\"\xb6\x01\n" +
	"\x19RemoteExecuteResultStream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x129\n" +
	"\x04type\x18\x03 \x01(\x0e2%.workers.RemoteExecuteResultEventTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"L\n" +
	"\x16RemoteExecuteResultAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xa7\x01\n" +
	"\x1fRemoteExecuteSubscribeEventType\x12*\n" +
	"&REMOTE_EXECUTE_SUBSCRIBE_EVENT_UNKNOWN\x10\x00\x12,\n" +
	"(REMOTE_EXECUTE_SUBSCRIBE_EVENT_CONNECTED\x10\x01\x12*\n" +
	"&REMOTE_EXECUTE_SUBSCRIBE_EVENT_COMMAND\x10\x02*\xc6\x01\n" +
	"\x1cRemoteExecuteResultEventType\x12!\n" +
	"\x1dREMOTE_EXECUTE_RESULT_UNKNOWN\x10\x00\x12 \n" +
	"\x1cREMOTE_EXECUTE_RESULT_STDOUT\x10\x01\x12 \n" +
	"\x1cREMOTE_EXECUTE_RESULT_STDERR\x10\x02\x12\x1e\n" +
	"\x1aREMOTE_EXECUTE_RESULT_EXIT\x10\x03\x12\x1f\n" +
	"\x1bREMOTE_EXECUTE_RESULT_ERROR\x10\x042\x9f\x05\n" +
	"\x0eWorkersService\x123\n" +
	"\x04Join\x12\x14.workers.JoinRequest\x1a\x15.workers.JoinResponse\x128\n" +
	"\x05Alive\x12\x15.workers.AliveRequest\x1a\x16.workers.AliveResponse0\x01\x12H\n" +
	"\vGetManifest\x12\x1b.workers.GetManifestRequest\x1a\x1c.workers.GetManifestResponse\x12>\n" +
	"\aStorage\x12\x17.workers.StorageRequest\x1a\x18.workers.StorageResponse0\x01\x12i\n" +
	"\x16ConnectInternalNetwork\x12&.workers.ConnectInternalNetworkRequest\x1a'.workers.ConnectInternalNetworkResponse\x12`\n" +
	"\x13BuiltinToolRegistry\x12#.workers.BuiltinToolRegistryRequest\x1a$.workers.BuiltinToolRegistryResponse\x12k\n" +
	"\x16RemoteExecuteSubscribe\x12&.workers.RemoteExecuteSubscribeRequest\x1a'.workers.RemoteExecuteSubscribeResponse0\x01\x12Z\n" +
	"\x13RemoteExecuteResult\x12\".workers.RemoteExecuteResultStream\x1a\x1f.workers.RemoteExecuteResultAckB\vZ\t./workersb\x06proto3"

var (
	file_workers_proto_rawDescOnce sync.Once
	file_workers_proto_rawDescData []byte
)

func file_workers_proto_rawDescGZIP() []byte {
	file_workers_proto_rawDescOnce.Do(func() {
		file_workers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_proto_rawDesc), len(file_workers_proto_rawDesc)))
	})
	return file_workers_proto_rawDescData
}

var file_workers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workers_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_workers_proto_goTypes = []any{
	(RemoteExecuteSubscribeEventType)(0),   // 0: workers.RemoteExecuteSubscribeEventType
	(RemoteExecuteResultEventType)(0),      // 1: workers.RemoteExecuteResultEventType
	(*JoinRequest)(nil),                    // 2: workers.JoinRequest
	(*WorkerMetadata)(nil),                 // 3: workers.WorkerMetadata
	(*JoinResponse)(nil),                   // 4: workers.JoinResponse
	(*AliveRequest)(nil),                   // 5: workers.AliveRequest
	(*AliveResponse)(nil),                  // 6: workers.AliveResponse
	(*GetManifestRequest)(nil),             // 7: workers.GetManifestRequest
	(*GetManifestResponse)(nil),            // 8: workers.GetManifestResponse
	(*StorageRequest)(nil),                 // 9: workers.StorageRequest
	(*StorageResponse)(nil),                // 10: workers.StorageResponse
	(*NetworkInterfaceMessage)(nil),        // 11: workers.NetworkInterfaceMessage
	(*ConnectInternalNetworkRequest)(nil),  // 12: workers.ConnectInternalNetworkRequest
	(*ConnectInternalNetworkResponse)(nil), // 13: workers.ConnectInternalNetworkResponse
	(*BuiltinToolRegistryRequest)(nil),     // 14: workers.BuiltinToolRegistryRequest
	(*BuiltinToolRegistryResponse)(nil),    // 15: workers.BuiltinToolRegistryResponse
	(*RemoteExecuteSubscribeRequest)(nil),  // 16: workers.RemoteExecuteSubscribeRequest
	(*RemoteExecuteSubscribeResponse)(nil), // 17: workers.RemoteExecuteSubscribeResponse
	(*RemoteExecuteResultStream)(nil),      // 18: workers.RemoteExecuteResultStream
	(*RemoteExecuteResultAck)(nil),         // 19: workers.RemoteExecuteResultAck
}
var file_workers_proto_depIdxs = []int32{
	3,  // 0: workers.JoinRequest.metadata:type_name -> workers.WorkerMetadata
	11, // 1: workers.ConnectInternalNetworkRequest.network_interfaces:type_name -> workers.NetworkInterfaceMessage
	0,  // 2: workers.RemoteExecuteSubscribeResponse.type:type_name -> workers.RemoteExecuteSubscribeEventType
	1,  // 3: workers.RemoteExecuteResultStream.type:type_name -> workers.RemoteExecuteResultEventType
	2,  // 4: workers.WorkersService.Join:input_type -> workers.JoinRequest
	5,  // 5: workers.WorkersService.Alive:input_type -> workers.AliveRequest
	7,  // 6: workers.WorkersService.GetManifest:input_type -> workers.GetManifestRequest
	9,  // 7: workers.WorkersService.Storage:input_type -> workers.StorageRequest
	12, // 8: workers.WorkersService.ConnectInternalNetwork:input_type -> workers.ConnectInternalNetworkRequest
	14, // 9: workers.WorkersService.BuiltinToolRegistry:input_type -> workers.BuiltinToolRegistryRequest
	16, // 10: workers.WorkersService.RemoteExecuteSubscribe:input_type -> workers.RemoteExecuteSubscribeRequest
	18, // 11: workers.WorkersService.RemoteExecuteResult:input_type -> workers.RemoteExecuteResultStream
	4,  // 12: workers.WorkersService.Join:output_type -> workers.JoinResponse
	6,  // 13: workers.WorkersService.Alive:output_type -> workers.AliveResponse
	8,  // 14: workers.WorkersService.GetManifest:output_type -> workers.GetManifestResponse
	10, // 15: workers.WorkersService.Storage:output_type -> workers.StorageResponse
	13, // 16: workers.WorkersService.ConnectInternalNetwork:output_type -> workers.ConnectInternalNetworkResponse
	15, // 17: workers.WorkersService.BuiltinToolRegistry:output_type -> workers.BuiltinToolRegistryResponse
	17, // 18: workers.WorkersService.RemoteExecuteSubscribe:output_type -> workers.RemoteExecuteSubscribeResponse
	19, // 19: workers.WorkersService.RemoteExecuteResult:output_type -> workers.RemoteExecuteResultAck
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_workers_proto_init() }
func file_workers_proto_init() {
	if File_workers_proto != nil {
		return
	}
	file_workers_proto_msgTypes[0].OneofWrappers = []any{}
	file_workers_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_proto_rawDesc), len(file_workers_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workers_proto_goTypes,
		DependencyIndexes: file_workers_proto_depIdxs,
		EnumInfos:         file_workers_proto_enumTypes,
		MessageInfos:      file_workers_proto_msgTypes,
	}.Build()
	File_workers_proto = out.File
	file_workers_proto_goTypes = nil
	file_workers_proto_depIdxs = nil
}
