// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: workers.proto

package workers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkersService_Join_FullMethodName                   = "/workers.WorkersService/Join"
	WorkersService_Alive_FullMethodName                  = "/workers.WorkersService/Alive"
	WorkersService_GetManifest_FullMethodName            = "/workers.WorkersService/GetManifest"
	WorkersService_Storage_FullMethodName                = "/workers.WorkersService/Storage"
	WorkersService_ConnectInternalNetwork_FullMethodName = "/workers.WorkersService/ConnectInternalNetwork"
	WorkersService_BuiltinToolRegistry_FullMethodName    = "/workers.WorkersService/BuiltinToolRegistry"
	WorkersService_ReportScannerStatus_FullMethodName    = "/workers.WorkersService/ReportScannerStatus"
	WorkersService_GetToolUpdatePlan_FullMethodName      = "/workers.WorkersService/GetToolUpdatePlan"
	WorkersService_ReportToolStatus_FullMethodName       = "/workers.WorkersService/ReportToolStatus"
)

// WorkersServiceClient is the client API for WorkersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkersServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Alive(ctx context.Context, in *AliveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AliveResponse], error)
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error)
	Storage(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StorageResponse], error)
	ConnectInternalNetwork(ctx context.Context, in *ConnectInternalNetworkRequest, opts ...grpc.CallOption) (*ConnectInternalNetworkResponse, error)
	BuiltinToolRegistry(ctx context.Context, in *BuiltinToolRegistryRequest, opts ...grpc.CallOption) (*BuiltinToolRegistryResponse, error)
	ReportScannerStatus(ctx context.Context, in *ScannerStatusReportRequest, opts ...grpc.CallOption) (*ScannerStatusReportResponse, error)
	GetToolUpdatePlan(ctx context.Context, in *ToolUpdatePlanRequest, opts ...grpc.CallOption) (*ToolUpdatePlanResponse, error)
	ReportToolStatus(ctx context.Context, in *ToolStatusReportRequest, opts ...grpc.CallOption) (*ToolStatusReportResponse, error)
}

type workersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkersServiceClient(cc grpc.ClientConnInterface) WorkersServiceClient {
	return &workersServiceClient{cc}
}

func (c *workersServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, WorkersService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersServiceClient) Alive(ctx context.Context, in *AliveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AliveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkersService_ServiceDesc.Streams[0], WorkersService_Alive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AliveRequest, AliveResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkersService_AliveClient = grpc.ServerStreamingClient[AliveResponse]

func (c *workersServiceClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManifestResponse)
	err := c.cc.Invoke(ctx, WorkersService_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersServiceClient) Storage(ctx context.Context, in *StorageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StorageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkersService_ServiceDesc.Streams[1], WorkersService_Storage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StorageRequest, StorageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkersService_StorageClient = grpc.ServerStreamingClient[StorageResponse]

func (c *workersServiceClient) ConnectInternalNetwork(ctx context.Context, in *ConnectInternalNetworkRequest, opts ...grpc.CallOption) (*ConnectInternalNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectInternalNetworkResponse)
	err := c.cc.Invoke(ctx, WorkersService_ConnectInternalNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersServiceClient) BuiltinToolRegistry(ctx context.Context, in *BuiltinToolRegistryRequest, opts ...grpc.CallOption) (*BuiltinToolRegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuiltinToolRegistryResponse)
	err := c.cc.Invoke(ctx, WorkersService_BuiltinToolRegistry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersServiceClient) ReportScannerStatus(ctx context.Context, in *ScannerStatusReportRequest, opts ...grpc.CallOption) (*ScannerStatusReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScannerStatusReportResponse)
	err := c.cc.Invoke(ctx, WorkersService_ReportScannerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersServiceClient) GetToolUpdatePlan(ctx context.Context, in *ToolUpdatePlanRequest, opts ...grpc.CallOption) (*ToolUpdatePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolUpdatePlanResponse)
	err := c.cc.Invoke(ctx, WorkersService_GetToolUpdatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workersServiceClient) ReportToolStatus(ctx context.Context, in *ToolStatusReportRequest, opts ...grpc.CallOption) (*ToolStatusReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolStatusReportResponse)
	err := c.cc.Invoke(ctx, WorkersService_ReportToolStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkersServiceServer is the server API for WorkersService service.
// All implementations must embed UnimplementedWorkersServiceServer
// for forward compatibility.
type WorkersServiceServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Alive(*AliveRequest, grpc.ServerStreamingServer[AliveResponse]) error
	GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error)
	Storage(*StorageRequest, grpc.ServerStreamingServer[StorageResponse]) error
	ConnectInternalNetwork(context.Context, *ConnectInternalNetworkRequest) (*ConnectInternalNetworkResponse, error)
	BuiltinToolRegistry(context.Context, *BuiltinToolRegistryRequest) (*BuiltinToolRegistryResponse, error)
	ReportScannerStatus(context.Context, *ScannerStatusReportRequest) (*ScannerStatusReportResponse, error)
	GetToolUpdatePlan(context.Context, *ToolUpdatePlanRequest) (*ToolUpdatePlanResponse, error)
	ReportToolStatus(context.Context, *ToolStatusReportRequest) (*ToolStatusReportResponse, error)
	mustEmbedUnimplementedWorkersServiceServer()
}

// UnimplementedWorkersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkersServiceServer struct{}

func (UnimplementedWorkersServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedWorkersServiceServer) Alive(*AliveRequest, grpc.ServerStreamingServer[AliveResponse]) error {
	return status.Error(codes.Unimplemented, "method Alive not implemented")
}
func (UnimplementedWorkersServiceServer) GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedWorkersServiceServer) Storage(*StorageRequest, grpc.ServerStreamingServer[StorageResponse]) error {
	return status.Error(codes.Unimplemented, "method Storage not implemented")
}
func (UnimplementedWorkersServiceServer) ConnectInternalNetwork(context.Context, *ConnectInternalNetworkRequest) (*ConnectInternalNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectInternalNetwork not implemented")
}
func (UnimplementedWorkersServiceServer) BuiltinToolRegistry(context.Context, *BuiltinToolRegistryRequest) (*BuiltinToolRegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuiltinToolRegistry not implemented")
}
func (UnimplementedWorkersServiceServer) ReportScannerStatus(context.Context, *ScannerStatusReportRequest) (*ScannerStatusReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportScannerStatus not implemented")
}
func (UnimplementedWorkersServiceServer) GetToolUpdatePlan(context.Context, *ToolUpdatePlanRequest) (*ToolUpdatePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToolUpdatePlan not implemented")
}
func (UnimplementedWorkersServiceServer) ReportToolStatus(context.Context, *ToolStatusReportRequest) (*ToolStatusReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportToolStatus not implemented")
}
func (UnimplementedWorkersServiceServer) mustEmbedUnimplementedWorkersServiceServer() {}
func (UnimplementedWorkersServiceServer) testEmbeddedByValue()                        {}

// UnsafeWorkersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkersServiceServer will
// result in compilation errors.
type UnsafeWorkersServiceServer interface {
	mustEmbedUnimplementedWorkersServiceServer()
}

func RegisterWorkersServiceServer(s grpc.ServiceRegistrar, srv WorkersServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkersService_ServiceDesc, srv)
}

func _WorkersService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkersService_Alive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AliveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkersServiceServer).Alive(m, &grpc.GenericServerStream[AliveRequest, AliveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkersService_AliveServer = grpc.ServerStreamingServer[AliveResponse]

func _WorkersService_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkersService_Storage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StorageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkersServiceServer).Storage(m, &grpc.GenericServerStream[StorageRequest, StorageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkersService_StorageServer = grpc.ServerStreamingServer[StorageResponse]

func _WorkersService_ConnectInternalNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectInternalNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).ConnectInternalNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_ConnectInternalNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).ConnectInternalNetwork(ctx, req.(*ConnectInternalNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkersService_BuiltinToolRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuiltinToolRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).BuiltinToolRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_BuiltinToolRegistry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).BuiltinToolRegistry(ctx, req.(*BuiltinToolRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkersService_ReportScannerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScannerStatusReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).ReportScannerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_ReportScannerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).ReportScannerStatus(ctx, req.(*ScannerStatusReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkersService_GetToolUpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolUpdatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).GetToolUpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_GetToolUpdatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).GetToolUpdatePlan(ctx, req.(*ToolUpdatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkersService_ReportToolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolStatusReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkersServiceServer).ReportToolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkersService_ReportToolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkersServiceServer).ReportToolStatus(ctx, req.(*ToolStatusReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkersService_ServiceDesc is the grpc.ServiceDesc for WorkersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workers.WorkersService",
	HandlerType: (*WorkersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _WorkersService_Join_Handler,
		},
		{
			MethodName: "GetManifest",
			Handler:    _WorkersService_GetManifest_Handler,
		},
		{
			MethodName: "ConnectInternalNetwork",
			Handler:    _WorkersService_ConnectInternalNetwork_Handler,
		},
		{
			MethodName: "BuiltinToolRegistry",
			Handler:    _WorkersService_BuiltinToolRegistry_Handler,
		},
		{
			MethodName: "ReportScannerStatus",
			Handler:    _WorkersService_ReportScannerStatus_Handler,
		},
		{
			MethodName: "GetToolUpdatePlan",
			Handler:    _WorkersService_GetToolUpdatePlan_Handler,
		},
		{
			MethodName: "ReportToolStatus",
			Handler:    _WorkersService_ReportToolStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Alive",
			Handler:       _WorkersService_Alive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Storage",
			Handler:       _WorkersService_Storage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workers.proto",
}
