// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: workers.proto

package workers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Token         *string                `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Metadata      *WorkerMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_workers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *JoinRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *JoinRequest) GetMetadata() *WorkerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WorkerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Os            *string                `protobuf:"bytes,2,opt,name=os,proto3,oneof" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMetadata) Reset() {
	*x = WorkerMetadata{}
	mi := &file_workers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMetadata) ProtoMessage() {}

func (x *WorkerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMetadata.ProtoReflect.Descriptor instead.
func (*WorkerMetadata) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *WorkerMetadata) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerToken   string                 `protobuf:"bytes,2,opt,name=worker_token,json=workerToken,proto3" json:"worker_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_workers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{2}
}

func (x *JoinResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JoinResponse) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerToken   string                 `protobuf:"bytes,1,opt,name=worker_token,json=workerToken,proto3" json:"worker_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveRequest) Reset() {
	*x = AliveRequest{}
	mi := &file_workers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveRequest) ProtoMessage() {}

func (x *AliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveRequest.ProtoReflect.Descriptor instead.
func (*AliveRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{3}
}

func (x *AliveRequest) GetWorkerToken() string {
	if x != nil {
		return x.WorkerToken
	}
	return ""
}

type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_workers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{4}
}

func (x *AliveResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *AliveResponse) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *AliveResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_workers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{5}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitCommands  []string               `protobuf:"bytes,1,rep,name=init_commands,json=initCommands,proto3" json:"init_commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_workers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{6}
}

func (x *GetManifestResponse) GetInitCommands() []string {
	if x != nil {
		return x.InitCommands
	}
	return nil
}

type StorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageRequest) Reset() {
	*x = StorageRequest{}
	mi := &file_workers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequest) ProtoMessage() {}

func (x *StorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequest.ProtoReflect.Descriptor instead.
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{7}
}

func (x *StorageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_workers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{8}
}

func (x *StorageResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *StorageResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StorageResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type NetworkInterfaceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Cidr          string                 `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	GatewayIp     string                 `protobuf:"bytes,4,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`
	GatewayMac    string                 `protobuf:"bytes,5,opt,name=gateway_mac,json=gatewayMac,proto3" json:"gateway_mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterfaceMessage) Reset() {
	*x = NetworkInterfaceMessage{}
	mi := &file_workers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceMessage) ProtoMessage() {}

func (x *NetworkInterfaceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceMessage.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceMessage) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkInterfaceMessage) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *NetworkInterfaceMessage) GetGatewayMac() string {
	if x != nil {
		return x.GatewayMac
	}
	return ""
}

type ConnectInternalNetworkRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	WorkerId          string                     `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	NetworkId         string                     `protobuf:"bytes,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	NetworkInterfaces []*NetworkInterfaceMessage `protobuf:"bytes,3,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectInternalNetworkRequest) Reset() {
	*x = ConnectInternalNetworkRequest{}
	mi := &file_workers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectInternalNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInternalNetworkRequest) ProtoMessage() {}

func (x *ConnectInternalNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInternalNetworkRequest.ProtoReflect.Descriptor instead.
func (*ConnectInternalNetworkRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectInternalNetworkRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ConnectInternalNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *ConnectInternalNetworkRequest) GetNetworkInterfaces() []*NetworkInterfaceMessage {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

type ConnectInternalNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectInternalNetworkResponse) Reset() {
	*x = ConnectInternalNetworkResponse{}
	mi := &file_workers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectInternalNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInternalNetworkResponse) ProtoMessage() {}

func (x *ConnectInternalNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInternalNetworkResponse.ProtoReflect.Descriptor instead.
func (*ConnectInternalNetworkResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectInternalNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BuiltinToolRegistryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`     // worker sends: runtime.GOOS (e.g., "linux")
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"` // worker sends: runtime.GOARCH (e.g., "arm64")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuiltinToolRegistryRequest) Reset() {
	*x = BuiltinToolRegistryRequest{}
	mi := &file_workers_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuiltinToolRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltinToolRegistryRequest) ProtoMessage() {}

func (x *BuiltinToolRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltinToolRegistryRequest.ProtoReflect.Descriptor instead.
func (*BuiltinToolRegistryRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{12}
}

func (x *BuiltinToolRegistryRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *BuiltinToolRegistryRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type BuiltinToolRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolPaths     []string               `protobuf:"bytes,1,rep,name=tool_paths,json=toolPaths,proto3" json:"tool_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuiltinToolRegistryResponse) Reset() {
	*x = BuiltinToolRegistryResponse{}
	mi := &file_workers_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuiltinToolRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltinToolRegistryResponse) ProtoMessage() {}

func (x *BuiltinToolRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltinToolRegistryResponse.ProtoReflect.Descriptor instead.
func (*BuiltinToolRegistryResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{13}
}

func (x *BuiltinToolRegistryResponse) GetToolPaths() []string {
	if x != nil {
		return x.ToolPaths
	}
	return nil
}

type ScannerStatusReportRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EngineVersion       string                 `protobuf:"bytes,1,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	TemplateVersion     string                 `protobuf:"bytes,2,opt,name=template_version,json=templateVersion,proto3" json:"template_version,omitempty"`
	TemplateSource      string                 `protobuf:"bytes,3,opt,name=template_source,json=templateSource,proto3" json:"template_source,omitempty"`
	State               string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	LastUpdateAttemptAt *string                `protobuf:"bytes,5,opt,name=last_update_attempt_at,json=lastUpdateAttemptAt,proto3,oneof" json:"last_update_attempt_at,omitempty"`
	LastUpdateSuccessAt *string                `protobuf:"bytes,6,opt,name=last_update_success_at,json=lastUpdateSuccessAt,proto3,oneof" json:"last_update_success_at,omitempty"`
	LastValidatedAt     *string                `protobuf:"bytes,7,opt,name=last_validated_at,json=lastValidatedAt,proto3,oneof" json:"last_validated_at,omitempty"`
	LastError           *string                `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScannerStatusReportRequest) Reset() {
	*x = ScannerStatusReportRequest{}
	mi := &file_workers_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerStatusReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerStatusReportRequest) ProtoMessage() {}

func (x *ScannerStatusReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerStatusReportRequest.ProtoReflect.Descriptor instead.
func (*ScannerStatusReportRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{14}
}

func (x *ScannerStatusReportRequest) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetTemplateVersion() string {
	if x != nil {
		return x.TemplateVersion
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetTemplateSource() string {
	if x != nil {
		return x.TemplateSource
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetLastUpdateAttemptAt() string {
	if x != nil && x.LastUpdateAttemptAt != nil {
		return *x.LastUpdateAttemptAt
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetLastUpdateSuccessAt() string {
	if x != nil && x.LastUpdateSuccessAt != nil {
		return *x.LastUpdateSuccessAt
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetLastValidatedAt() string {
	if x != nil && x.LastValidatedAt != nil {
		return *x.LastValidatedAt
	}
	return ""
}

func (x *ScannerStatusReportRequest) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

type ScannerStatusReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScannerStatusReportResponse) Reset() {
	*x = ScannerStatusReportResponse{}
	mi := &file_workers_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerStatusReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerStatusReportResponse) ProtoMessage() {}

func (x *ScannerStatusReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerStatusReportResponse.ProtoReflect.Descriptor instead.
func (*ScannerStatusReportResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{15}
}

func (x *ScannerStatusReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ToolUpdatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUpdatePlanRequest) Reset() {
	*x = ToolUpdatePlanRequest{}
	mi := &file_workers_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUpdatePlanRequest) ProtoMessage() {}

func (x *ToolUpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*ToolUpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{16}
}

func (x *ToolUpdatePlanRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ToolUpdatePlanRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ToolUpdateDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	TargetVersion string                 `protobuf:"bytes,3,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	ArtifactName  *string                `protobuf:"bytes,5,opt,name=artifact_name,json=artifactName,proto3,oneof" json:"artifact_name,omitempty"`
	ArtifactUrl   *string                `protobuf:"bytes,6,opt,name=artifact_url,json=artifactUrl,proto3,oneof" json:"artifact_url,omitempty"`
	Sha256        *string                `protobuf:"bytes,7,opt,name=sha256,proto3,oneof" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUpdateDirective) Reset() {
	*x = ToolUpdateDirective{}
	mi := &file_workers_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUpdateDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUpdateDirective) ProtoMessage() {}

func (x *ToolUpdateDirective) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUpdateDirective.ProtoReflect.Descriptor instead.
func (*ToolUpdateDirective) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{17}
}

func (x *ToolUpdateDirective) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ToolUpdateDirective) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ToolUpdateDirective) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *ToolUpdateDirective) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ToolUpdateDirective) GetArtifactName() string {
	if x != nil && x.ArtifactName != nil {
		return *x.ArtifactName
	}
	return ""
}

func (x *ToolUpdateDirective) GetArtifactUrl() string {
	if x != nil && x.ArtifactUrl != nil {
		return *x.ArtifactUrl
	}
	return ""
}

func (x *ToolUpdateDirective) GetSha256() string {
	if x != nil && x.Sha256 != nil {
		return *x.Sha256
	}
	return ""
}

type ToolUpdatePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*ToolUpdateDirective `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUpdatePlanResponse) Reset() {
	*x = ToolUpdatePlanResponse{}
	mi := &file_workers_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUpdatePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUpdatePlanResponse) ProtoMessage() {}

func (x *ToolUpdatePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUpdatePlanResponse.ProtoReflect.Descriptor instead.
func (*ToolUpdatePlanResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{18}
}

func (x *ToolUpdatePlanResponse) GetUpdates() []*ToolUpdateDirective {
	if x != nil {
		return x.Updates
	}
	return nil
}

type ToolStatusReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Component        string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	InstalledVersion *string                `protobuf:"bytes,2,opt,name=installed_version,json=installedVersion,proto3,oneof" json:"installed_version,omitempty"`
	State            string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	RequestId        *string                `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	TargetVersion    *string                `protobuf:"bytes,5,opt,name=target_version,json=targetVersion,proto3,oneof" json:"target_version,omitempty"`
	RollbackVersion  *string                `protobuf:"bytes,6,opt,name=rollback_version,json=rollbackVersion,proto3,oneof" json:"rollback_version,omitempty"`
	LastAttemptAt    *string                `protobuf:"bytes,7,opt,name=last_attempt_at,json=lastAttemptAt,proto3,oneof" json:"last_attempt_at,omitempty"`
	LastSuccessAt    *string                `protobuf:"bytes,8,opt,name=last_success_at,json=lastSuccessAt,proto3,oneof" json:"last_success_at,omitempty"`
	Error            *string                `protobuf:"bytes,9,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolStatusReportRequest) Reset() {
	*x = ToolStatusReportRequest{}
	mi := &file_workers_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatusReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatusReportRequest) ProtoMessage() {}

func (x *ToolStatusReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatusReportRequest.ProtoReflect.Descriptor instead.
func (*ToolStatusReportRequest) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{19}
}

func (x *ToolStatusReportRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ToolStatusReportRequest) GetInstalledVersion() string {
	if x != nil && x.InstalledVersion != nil {
		return *x.InstalledVersion
	}
	return ""
}

func (x *ToolStatusReportRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ToolStatusReportRequest) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *ToolStatusReportRequest) GetTargetVersion() string {
	if x != nil && x.TargetVersion != nil {
		return *x.TargetVersion
	}
	return ""
}

func (x *ToolStatusReportRequest) GetRollbackVersion() string {
	if x != nil && x.RollbackVersion != nil {
		return *x.RollbackVersion
	}
	return ""
}

func (x *ToolStatusReportRequest) GetLastAttemptAt() string {
	if x != nil && x.LastAttemptAt != nil {
		return *x.LastAttemptAt
	}
	return ""
}

func (x *ToolStatusReportRequest) GetLastSuccessAt() string {
	if x != nil && x.LastSuccessAt != nil {
		return *x.LastSuccessAt
	}
	return ""
}

func (x *ToolStatusReportRequest) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ToolStatusReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolStatusReportResponse) Reset() {
	*x = ToolStatusReportResponse{}
	mi := &file_workers_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatusReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatusReportResponse) ProtoMessage() {}

func (x *ToolStatusReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workers_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatusReportResponse.ProtoReflect.Descriptor instead.
func (*ToolStatusReportResponse) Descriptor() ([]byte, []int) {
	return file_workers_proto_rawDescGZIP(), []int{20}
}

func (x *ToolStatusReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_workers_proto protoreflect.FileDescriptor

const file_workers_proto_rawDesc = "" +
	"\n" +
	"\rworkers.proto\x12\aworkers\"\xa3\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\x05token\x18\x03 \x01(\tH\x00R\x05token\x88\x01\x01\x128\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.workers.WorkerMetadataH\x01R\bmetadata\x88\x01\x01B\b\n" +
	"\x06_tokenB\v\n" +
	"\t_metadataJ\x04\b\x02\x10\x03R\tsignature\"N\n" +
	"\x0eWorkerMetadata\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02os\x18\x02 \x01(\tH\x01R\x02os\x88\x01\x01B\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_os\"N\n" +
	"\fJoinResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fworker_token\x18\x02 \x01(\tR\vworkerToken\"1\n" +
	"\fAliveRequest\x12!\n" +
	"\fworker_token\x18\x01 \x01(\tR\vworkerToken\"d\n" +
	"\rAliveResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12 \n" +
	"\flast_seen_at\x18\x02 \x01(\tR\n" +
	"lastSeenAt\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\x14\n" +
	"\x12GetManifestRequest\":\n" +
	"\x13GetManifestResponse\x12#\n" +
	"\rinit_commands\x18\x01 \x03(\tR\finitCommands\"$\n" +
	"\x0eStorageRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"Q\n" +
	"\x0fStorageResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"\xb3\x01\n" +
	"\x17NetworkInterfaceMessage\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04cidr\x18\x03 \x01(\tR\x04cidr\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\x04 \x01(\tR\tgatewayIp\x12\x1f\n" +
	"\vgateway_mac\x18\x05 \x01(\tR\n" +
	"gatewayMac\"\xac\x01\n" +
	"\x1dConnectInternalNetworkRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\tR\tnetworkId\x12O\n" +
	"\x12network_interfaces\x18\x03 \x03(\v2 .workers.NetworkInterfaceMessageR\x11networkInterfaces\":\n" +
	"\x1eConnectInternalNetworkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x1aBuiltinToolRegistryRequest\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"<\n" +
	"\x1bBuiltinToolRegistryResponse\x12\x1d\n" +
	"\n" +
	"tool_paths\x18\x01 \x03(\tR\ttoolPaths\"\xd1\x03\n" +
	"\x1aScannerStatusReportRequest\x12%\n" +
	"\x0eengine_version\x18\x01 \x01(\tR\rengineVersion\x12)\n" +
	"\x10template_version\x18\x02 \x01(\tR\x0ftemplateVersion\x12'\n" +
	"\x0ftemplate_source\x18\x03 \x01(\tR\x0etemplateSource\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x128\n" +
	"\x16last_update_attempt_at\x18\x05 \x01(\tH\x00R\x13lastUpdateAttemptAt\x88\x01\x01\x128\n" +
	"\x16last_update_success_at\x18\x06 \x01(\tH\x01R\x13lastUpdateSuccessAt\x88\x01\x01\x12/\n" +
	"\x11last_validated_at\x18\a \x01(\tH\x02R\x0flastValidatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"last_error\x18\b \x01(\tH\x03R\tlastError\x88\x01\x01B\x19\n" +
	"\x17_last_update_attempt_atB\x19\n" +
	"\x17_last_update_success_atB\x14\n" +
	"\x12_last_validated_atB\r\n" +
	"\v_last_error\"7\n" +
	"\x1bScannerStatusReportResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\";\n" +
	"\x15ToolUpdatePlanRequest\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"\xaa\x02\n" +
	"\x13ToolUpdateDirective\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12%\n" +
	"\x0etarget_version\x18\x03 \x01(\tR\rtargetVersion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12(\n" +
	"\rartifact_name\x18\x05 \x01(\tH\x00R\fartifactName\x88\x01\x01\x12&\n" +
	"\fartifact_url\x18\x06 \x01(\tH\x01R\vartifactUrl\x88\x01\x01\x12\x1b\n" +
	"\x06sha256\x18\a \x01(\tH\x02R\x06sha256\x88\x01\x01B\x10\n" +
	"\x0e_artifact_nameB\x0f\n" +
	"\r_artifact_urlB\t\n" +
	"\a_sha256\"P\n" +
	"\x16ToolUpdatePlanResponse\x126\n" +
	"\aupdates\x18\x01 \x03(\v2\x1c.workers.ToolUpdateDirectiveR\aupdates\"\xf3\x03\n" +
	"\x17ToolStatusReportRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x120\n" +
	"\x11installed_version\x18\x02 \x01(\tH\x00R\x10installedVersion\x88\x01\x01\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\"\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tH\x01R\trequestId\x88\x01\x01\x12*\n" +
	"\x0etarget_version\x18\x05 \x01(\tH\x02R\rtargetVersion\x88\x01\x01\x12.\n" +
	"\x10rollback_version\x18\x06 \x01(\tH\x03R\x0frollbackVersion\x88\x01\x01\x12+\n" +
	"\x0flast_attempt_at\x18\a \x01(\tH\x04R\rlastAttemptAt\x88\x01\x01\x12+\n" +
	"\x0flast_success_at\x18\b \x01(\tH\x05R\rlastSuccessAt\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\t \x01(\tH\x06R\x05error\x88\x01\x01B\x14\n" +
	"\x12_installed_versionB\r\n" +
	"\v_request_idB\x11\n" +
	"\x0f_target_versionB\x13\n" +
	"\x11_rollback_versionB\x12\n" +
	"\x10_last_attempt_atB\x12\n" +
	"\x10_last_success_atB\b\n" +
	"\x06_error\"4\n" +
	"\x18ToolStatusReportResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xe7\x05\n" +
	"\x0eWorkersService\x123\n" +
	"\x04Join\x12\x14.workers.JoinRequest\x1a\x15.workers.JoinResponse\x128\n" +
	"\x05Alive\x12\x15.workers.AliveRequest\x1a\x16.workers.AliveResponse0\x01\x12H\n" +
	"\vGetManifest\x12\x1b.workers.GetManifestRequest\x1a\x1c.workers.GetManifestResponse\x12>\n" +
	"\aStorage\x12\x17.workers.StorageRequest\x1a\x18.workers.StorageResponse0\x01\x12i\n" +
	"\x16ConnectInternalNetwork\x12&.workers.ConnectInternalNetworkRequest\x1a'.workers.ConnectInternalNetworkResponse\x12`\n" +
	"\x13BuiltinToolRegistry\x12#.workers.BuiltinToolRegistryRequest\x1a$.workers.BuiltinToolRegistryResponse\x12`\n" +
	"\x13ReportScannerStatus\x12#.workers.ScannerStatusReportRequest\x1a$.workers.ScannerStatusReportResponse\x12T\n" +
	"\x11GetToolUpdatePlan\x12\x1e.workers.ToolUpdatePlanRequest\x1a\x1f.workers.ToolUpdatePlanResponse\x12W\n" +
	"\x10ReportToolStatus\x12 .workers.ToolStatusReportRequest\x1a!.workers.ToolStatusReportResponseB\vZ\t./workersb\x06proto3"

var (
	file_workers_proto_rawDescOnce sync.Once
	file_workers_proto_rawDescData []byte
)

func file_workers_proto_rawDescGZIP() []byte {
	file_workers_proto_rawDescOnce.Do(func() {
		file_workers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workers_proto_rawDesc), len(file_workers_proto_rawDesc)))
	})
	return file_workers_proto_rawDescData
}

var file_workers_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_workers_proto_goTypes = []any{
	(*JoinRequest)(nil),                    // 0: workers.JoinRequest
	(*WorkerMetadata)(nil),                 // 1: workers.WorkerMetadata
	(*JoinResponse)(nil),                   // 2: workers.JoinResponse
	(*AliveRequest)(nil),                   // 3: workers.AliveRequest
	(*AliveResponse)(nil),                  // 4: workers.AliveResponse
	(*GetManifestRequest)(nil),             // 5: workers.GetManifestRequest
	(*GetManifestResponse)(nil),            // 6: workers.GetManifestResponse
	(*StorageRequest)(nil),                 // 7: workers.StorageRequest
	(*StorageResponse)(nil),                // 8: workers.StorageResponse
	(*NetworkInterfaceMessage)(nil),        // 9: workers.NetworkInterfaceMessage
	(*ConnectInternalNetworkRequest)(nil),  // 10: workers.ConnectInternalNetworkRequest
	(*ConnectInternalNetworkResponse)(nil), // 11: workers.ConnectInternalNetworkResponse
	(*BuiltinToolRegistryRequest)(nil),     // 12: workers.BuiltinToolRegistryRequest
	(*BuiltinToolRegistryResponse)(nil),    // 13: workers.BuiltinToolRegistryResponse
	(*ScannerStatusReportRequest)(nil),     // 14: workers.ScannerStatusReportRequest
	(*ScannerStatusReportResponse)(nil),    // 15: workers.ScannerStatusReportResponse
	(*ToolUpdatePlanRequest)(nil),          // 16: workers.ToolUpdatePlanRequest
	(*ToolUpdateDirective)(nil),            // 17: workers.ToolUpdateDirective
	(*ToolUpdatePlanResponse)(nil),         // 18: workers.ToolUpdatePlanResponse
	(*ToolStatusReportRequest)(nil),        // 19: workers.ToolStatusReportRequest
	(*ToolStatusReportResponse)(nil),       // 20: workers.ToolStatusReportResponse
}
var file_workers_proto_depIdxs = []int32{
	1,  // 0: workers.JoinRequest.metadata:type_name -> workers.WorkerMetadata
	9,  // 1: workers.ConnectInternalNetworkRequest.network_interfaces:type_name -> workers.NetworkInterfaceMessage
	17, // 2: workers.ToolUpdatePlanResponse.updates:type_name -> workers.ToolUpdateDirective
	0,  // 3: workers.WorkersService.Join:input_type -> workers.JoinRequest
	3,  // 4: workers.WorkersService.Alive:input_type -> workers.AliveRequest
	5,  // 5: workers.WorkersService.GetManifest:input_type -> workers.GetManifestRequest
	7,  // 6: workers.WorkersService.Storage:input_type -> workers.StorageRequest
	10, // 7: workers.WorkersService.ConnectInternalNetwork:input_type -> workers.ConnectInternalNetworkRequest
	12, // 8: workers.WorkersService.BuiltinToolRegistry:input_type -> workers.BuiltinToolRegistryRequest
	14, // 9: workers.WorkersService.ReportScannerStatus:input_type -> workers.ScannerStatusReportRequest
	16, // 10: workers.WorkersService.GetToolUpdatePlan:input_type -> workers.ToolUpdatePlanRequest
	19, // 11: workers.WorkersService.ReportToolStatus:input_type -> workers.ToolStatusReportRequest
	2,  // 12: workers.WorkersService.Join:output_type -> workers.JoinResponse
	4,  // 13: workers.WorkersService.Alive:output_type -> workers.AliveResponse
	6,  // 14: workers.WorkersService.GetManifest:output_type -> workers.GetManifestResponse
	8,  // 15: workers.WorkersService.Storage:output_type -> workers.StorageResponse
	11, // 16: workers.WorkersService.ConnectInternalNetwork:output_type -> workers.ConnectInternalNetworkResponse
	13, // 17: workers.WorkersService.BuiltinToolRegistry:output_type -> workers.BuiltinToolRegistryResponse
	15, // 18: workers.WorkersService.ReportScannerStatus:output_type -> workers.ScannerStatusReportResponse
	18, // 19: workers.WorkersService.GetToolUpdatePlan:output_type -> workers.ToolUpdatePlanResponse
	20, // 20: workers.WorkersService.ReportToolStatus:output_type -> workers.ToolStatusReportResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_workers_proto_init() }
func file_workers_proto_init() {
	if File_workers_proto != nil {
		return
	}
	file_workers_proto_msgTypes[0].OneofWrappers = []any{}
	file_workers_proto_msgTypes[1].OneofWrappers = []any{}
	file_workers_proto_msgTypes[14].OneofWrappers = []any{}
	file_workers_proto_msgTypes[17].OneofWrappers = []any{}
	file_workers_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workers_proto_rawDesc), len(file_workers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workers_proto_goTypes,
		DependencyIndexes: file_workers_proto_depIdxs,
		MessageInfos:      file_workers_proto_msgTypes,
	}.Build()
	File_workers_proto = out.File
	file_workers_proto_goTypes = nil
	file_workers_proto_depIdxs = nil
}
