// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "jobs_registry.proto" (package "jobs_registry", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { JobsRegistryService } from "./jobs_registry";
import type { ControlResponse } from "./jobs_registry";
import type { ControlRequest } from "./jobs_registry";
import type { JobResponse } from "./jobs_registry";
import type { JobResultRequest } from "./jobs_registry";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Job } from "./jobs_registry";
import type { Worker } from "./jobs_registry";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Service Definition
 *
 * @generated from protobuf service jobs_registry.JobsRegistryService
 */
export interface IJobsRegistryServiceClient {
    /**
     * @generated from protobuf rpc: Next
     */
    next(input: Worker, options?: RpcOptions): UnaryCall<Worker, Job>;
    /**
     * @generated from protobuf rpc: Result
     */
    result(input: JobResultRequest, options?: RpcOptions): UnaryCall<JobResultRequest, JobResponse>;
    /**
     * Control-plane poll: the worker reports its active job IDs and receives
     * per-job directives (stop/pause/resume) plus desired runtime settings.
     *
     * @generated from protobuf rpc: Control
     */
    control(input: ControlRequest, options?: RpcOptions): UnaryCall<ControlRequest, ControlResponse>;
}
/**
 * Service Definition
 *
 * @generated from protobuf service jobs_registry.JobsRegistryService
 */
export class JobsRegistryServiceClient implements IJobsRegistryServiceClient, ServiceInfo {
    typeName = JobsRegistryService.typeName;
    methods = JobsRegistryService.methods;
    options = JobsRegistryService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Next
     */
    next(input: Worker, options?: RpcOptions): UnaryCall<Worker, Job> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Worker, Job>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Result
     */
    result(input: JobResultRequest, options?: RpcOptions): UnaryCall<JobResultRequest, JobResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<JobResultRequest, JobResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Control-plane poll: the worker reports its active job IDs and receives
     * per-job directives (stop/pause/resume) plus desired runtime settings.
     *
     * @generated from protobuf rpc: Control
     */
    control(input: ControlRequest, options?: RpcOptions): UnaryCall<ControlRequest, ControlResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ControlRequest, ControlResponse>("unary", this._transport, method, opt, input);
    }
}
