// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "jobs_registry.proto" (package "jobs_registry", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Struct } from "./google/protobuf/struct";
import { Timestamp } from "./google/protobuf/timestamp";
// --- Request/Response Messages ---

/**
 * @generated from protobuf message jobs_registry.Worker
 */
export interface Worker {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message jobs_registry.ControlRequest
 */
export interface ControlRequest {
    /**
     * @generated from protobuf field: string worker_id = 1
     */
    workerId: string;
    /**
     * Job IDs the worker is currently executing (including paused ones).
     *
     * @generated from protobuf field: repeated string active_job_ids = 2
     */
    activeJobIds: string[];
}
/**
 * @generated from protobuf message jobs_registry.JobDirective
 */
export interface JobDirective {
    /**
     * @generated from protobuf field: string job_id = 1
     */
    jobId: string;
    /**
     * @generated from protobuf field: jobs_registry.JobControlAction action = 2
     */
    action: JobControlAction;
}
/**
 * @generated from protobuf message jobs_registry.ControlResponse
 */
export interface ControlResponse {
    /**
     * @generated from protobuf field: repeated jobs_registry.JobDirective directives = 1
     */
    directives: JobDirective[];
    /**
     * Desired concurrent-job limit; 0 = keep the worker's local default.
     *
     * @generated from protobuf field: int32 max_concurrency = 2
     */
    maxConcurrency: number;
    /**
     * Worker-level pause: stop pulling new jobs (running jobs unaffected).
     *
     * @generated from protobuf field: bool dispatch_paused = 3
     */
    dispatchPaused: boolean;
}
/**
 * @generated from protobuf message jobs_registry.Job
 */
export interface Job {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: jobs_registry.Asset asset = 2
     */
    asset?: Asset;
    /**
     * @generated from protobuf field: optional string command = 3
     */
    command?: string;
}
/**
 * @generated from protobuf message jobs_registry.JobResponse
 */
export interface JobResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message jobs_registry.JobResultRequest
 */
export interface JobResultRequest {
    /**
     * @generated from protobuf field: string worker_id = 1
     */
    workerId: string;
    /**
     * @generated from protobuf field: jobs_registry.UpdateResultDto data = 2
     */
    data?: UpdateResultDto;
}
/**
 * @generated from protobuf message jobs_registry.UpdateResultDto
 */
export interface UpdateResultDto {
    /**
     * @generated from protobuf field: string job_id = 1
     */
    jobId: string;
    /**
     * @generated from protobuf field: jobs_registry.DataPayloadResult data = 2
     */
    data?: DataPayloadResult;
}
/**
 * @generated from protobuf message jobs_registry.DataPayloadResult
 */
export interface DataPayloadResult {
    /**
     * @generated from protobuf field: bool error = 1
     */
    error: boolean;
    /**
     * @generated from protobuf field: optional string raw = 2
     */
    raw?: string;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "assets";
        /**
         * @generated from protobuf field: jobs_registry.AssetList assets = 3
         */
        assets: AssetList;
    } | {
        oneofKind: "httpResponse";
        /**
         * @generated from protobuf field: jobs_registry.HttpResponse http_response = 4
         */
        httpResponse: HttpResponse;
    } | {
        oneofKind: "numbers";
        /**
         * @generated from protobuf field: jobs_registry.NumberList numbers = 5
         */
        numbers: NumberList;
    } | {
        oneofKind: "vulnerabilities";
        /**
         * @generated from protobuf field: jobs_registry.VulnerabilityList vulnerabilities = 6
         */
        vulnerabilities: VulnerabilityList;
    } | {
        oneofKind: "assetTags";
        /**
         * @generated from protobuf field: jobs_registry.AssetTagList asset_tags = 7
         */
        assetTags: AssetTagList;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message jobs_registry.AssetList
 */
export interface AssetList {
    /**
     * @generated from protobuf field: repeated jobs_registry.Asset values = 1
     */
    values: Asset[];
}
/**
 * @generated from protobuf message jobs_registry.NumberList
 */
export interface NumberList {
    /**
     * @generated from protobuf field: repeated int32 values = 1
     */
    values: number[];
}
/**
 * @generated from protobuf message jobs_registry.VulnerabilityList
 */
export interface VulnerabilityList {
    /**
     * @generated from protobuf field: repeated jobs_registry.Vulnerability values = 1
     */
    values: Vulnerability[];
}
/**
 * @generated from protobuf message jobs_registry.AssetTagList
 */
export interface AssetTagList {
    /**
     * @generated from protobuf field: repeated jobs_registry.AssetTag values = 1
     */
    values: AssetTag[];
}
/**
 * @generated from protobuf message jobs_registry.Asset
 */
export interface Asset {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 3
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: string value = 4
     */
    value: string;
    /**
     * @generated from protobuf field: string target_id = 5
     */
    targetId: string;
    /**
     * @generated from protobuf field: bool is_primary = 6
     */
    isPrimary: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Struct dns_records = 7
     */
    dnsRecords?: Struct;
    /**
     * @generated from protobuf field: bool is_enabled = 8
     */
    isEnabled: boolean;
}
/**
 * @generated from protobuf message jobs_registry.HttpResponse
 */
export interface HttpResponse {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 2
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp timestamp = 3
     */
    timestamp?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Struct tls = 4
     */
    tls?: Struct;
    /**
     * @generated from protobuf field: string port = 5
     */
    port: string;
    /**
     * @generated from protobuf field: string url = 6
     */
    url: string;
    /**
     * @generated from protobuf field: string input = 7
     */
    input: string;
    /**
     * @generated from protobuf field: string title = 8
     */
    title: string;
    /**
     * @generated from protobuf field: string scheme = 9
     */
    scheme: string;
    /**
     * @generated from protobuf field: string webserver = 10
     */
    webserver: string;
    /**
     * @generated from protobuf field: string body = 11
     */
    body: string;
    /**
     * @generated from protobuf field: string content_type = 12
     */
    contentType: string;
    /**
     * @generated from protobuf field: string method = 13
     */
    method: string;
    /**
     * @generated from protobuf field: string host = 14
     */
    host: string;
    /**
     * @generated from protobuf field: string path = 15
     */
    path: string;
    /**
     * @generated from protobuf field: string favicon = 16
     */
    favicon: string;
    /**
     * @generated from protobuf field: string favicon_md5 = 17
     */
    faviconMd5: string;
    /**
     * @generated from protobuf field: string favicon_url = 18
     */
    faviconUrl: string;
    /**
     * @generated from protobuf field: google.protobuf.Struct header = 19
     */
    header?: Struct; // jsonb
    /**
     * @generated from protobuf field: string raw_header = 20
     */
    rawHeader: string;
    /**
     * @generated from protobuf field: string request = 21
     */
    request: string;
    /**
     * @generated from protobuf field: string time = 22
     */
    time: string;
    /**
     * @generated from protobuf field: repeated string a = 23
     */
    a: string[];
    /**
     * @generated from protobuf field: repeated string tech = 24
     */
    tech: string[];
    /**
     * @generated from protobuf field: int32 words = 25
     */
    words: number;
    /**
     * @generated from protobuf field: int32 lines = 26
     */
    lines: number;
    /**
     * @generated from protobuf field: int32 status_code = 27
     */
    statusCode: number;
    /**
     * @generated from protobuf field: int32 content_length = 28
     */
    contentLength: number;
    /**
     * @generated from protobuf field: bool failed = 29
     */
    failed: boolean;
    /**
     * @generated from protobuf field: google.protobuf.Struct knowledgebase = 30
     */
    knowledgebase?: Struct; // jsonb
    /**
     * @generated from protobuf field: repeated string resolvers = 31
     */
    resolvers: string[];
    /**
     * @generated from protobuf field: repeated string chain_status_codes = 32
     */
    chainStatusCodes: string[];
    /**
     * @generated from protobuf field: string asset_service_id = 33
     */
    assetServiceId: string;
    /**
     * @generated from protobuf field: string job_history_id = 34
     */
    jobHistoryId: string;
}
/**
 * @generated from protobuf message jobs_registry.Vulnerability
 */
export interface Vulnerability {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: string synopsis = 4
     */
    synopsis: string;
    /**
     * @generated from protobuf field: jobs_registry.Severity severity = 5
     */
    severity: Severity;
    /**
     * @generated from protobuf field: repeated string tags = 6
     */
    tags: string[];
    /**
     * @generated from protobuf field: repeated string references = 7
     */
    references: string[];
    /**
     * @generated from protobuf field: repeated string authors = 8
     */
    authors: string[];
    /**
     * @generated from protobuf field: string affected_url = 9
     */
    affectedUrl: string;
    /**
     * @generated from protobuf field: string ip_address = 10
     */
    ipAddress: string;
    /**
     * @generated from protobuf field: string host = 11
     */
    host: string;
    /**
     * @generated from protobuf field: repeated string ports = 12
     */
    ports: string[];
    /**
     * @generated from protobuf field: string cvss_metric = 13
     */
    cvssMetric: string;
    /**
     * @generated from protobuf field: float cvss_score = 14
     */
    cvssScore: number;
    /**
     * @generated from protobuf field: float epss_score = 15
     */
    epssScore: number;
    /**
     * @generated from protobuf field: float vpr_score = 16
     */
    vprScore: number;
    /**
     * @generated from protobuf field: repeated string cve_id = 17
     */
    cveId: string[];
    /**
     * @generated from protobuf field: repeated string bid_id = 18
     */
    bidId: string[];
    /**
     * @generated from protobuf field: repeated string cwe_id = 19
     */
    cweId: string[];
    /**
     * @generated from protobuf field: repeated string cea_id = 20
     */
    ceaId: string[];
    /**
     * @generated from protobuf field: repeated string iava = 21
     */
    iava: string[];
    /**
     * @generated from protobuf field: string cve_url = 22
     */
    cveUrl: string;
    /**
     * @generated from protobuf field: string cwe_url = 23
     */
    cweUrl: string;
    /**
     * @generated from protobuf field: string solution = 24
     */
    solution: string;
    /**
     * @generated from protobuf field: string extractor_name = 25
     */
    extractorName: string;
    /**
     * @generated from protobuf field: repeated string extracted_results = 26
     */
    extractedResults: string[];
    /**
     * @generated from protobuf field: google.protobuf.Timestamp publication_date = 27
     */
    publicationDate?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp modification_date = 28
     */
    modificationDate?: Timestamp;
    /**
     * @generated from protobuf field: string tool_id = 29
     */
    toolId: string; // Relation ID
    /**
     * @generated from protobuf field: string asset_id = 30
     */
    assetId: string; // Relation ID
    /**
     * @generated from protobuf field: string file_path = 31
     */
    filePath: string;
    /**
     * @generated from protobuf field: string job_history_id = 32
     */
    jobHistoryId: string;
    /**
     * @generated from protobuf field: bool is_archived = 33
     */
    isArchived: boolean;
    /**
     * @generated from protobuf field: string fingerprint = 34
     */
    fingerprint: string;
}
/**
 * @generated from protobuf message jobs_registry.AssetTag
 */
export interface AssetTag {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string tag = 2
     */
    tag: string;
    /**
     * @generated from protobuf field: string asset_service_id = 3
     */
    assetServiceId: string;
    /**
     * @generated from protobuf field: string tool_id = 4
     */
    toolId: string;
}
/**
 * @generated from protobuf enum jobs_registry.JobControlAction
 */
export enum JobControlAction {
    /**
     * @generated from protobuf enum value: JOB_CONTROL_NONE = 0;
     */
    JOB_CONTROL_NONE = 0,
    /**
     * Kill the running process; core has already marked the job cancelled.
     *
     * @generated from protobuf enum value: JOB_CONTROL_STOP = 1;
     */
    JOB_CONTROL_STOP = 1,
    /**
     * Suspend the scan process group (SIGSTOP); slot stays occupied.
     *
     * @generated from protobuf enum value: JOB_CONTROL_PAUSE = 2;
     */
    JOB_CONTROL_PAUSE = 2,
    /**
     * Continue a previously paused process (no-op when not paused).
     *
     * @generated from protobuf enum value: JOB_CONTROL_RESUME = 3;
     */
    JOB_CONTROL_RESUME = 3
}
// --- Enums ---

/**
 * @generated from protobuf enum jobs_registry.Severity
 */
export enum Severity {
    /**
     * @generated from protobuf enum value: INFO = 0;
     */
    INFO = 0,
    /**
     * @generated from protobuf enum value: LOW = 1;
     */
    LOW = 1,
    /**
     * @generated from protobuf enum value: MEDIUM = 2;
     */
    MEDIUM = 2,
    /**
     * @generated from protobuf enum value: HIGH = 3;
     */
    HIGH = 3,
    /**
     * @generated from protobuf enum value: CRITICAL = 4;
     */
    CRITICAL = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class Worker$Type extends MessageType<Worker> {
    constructor() {
        super("jobs_registry.Worker", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Worker>): Worker {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<Worker>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Worker): Worker {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Worker, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.Worker
 */
export const Worker = new Worker$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ControlRequest$Type extends MessageType<ControlRequest> {
    constructor() {
        super("jobs_registry.ControlRequest", [
            { no: 1, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "active_job_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ControlRequest>): ControlRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerId = "";
        message.activeJobIds = [];
        if (value !== undefined)
            reflectionMergePartial<ControlRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ControlRequest): ControlRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_id */ 1:
                    message.workerId = reader.string();
                    break;
                case /* repeated string active_job_ids */ 2:
                    message.activeJobIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ControlRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_id = 1; */
        if (message.workerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerId);
        /* repeated string active_job_ids = 2; */
        for (let i = 0; i < message.activeJobIds.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.activeJobIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.ControlRequest
 */
export const ControlRequest = new ControlRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JobDirective$Type extends MessageType<JobDirective> {
    constructor() {
        super("jobs_registry.JobDirective", [
            { no: 1, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "action", kind: "enum", T: () => ["jobs_registry.JobControlAction", JobControlAction] }
        ]);
    }
    create(value?: PartialMessage<JobDirective>): JobDirective {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = "";
        message.action = 0;
        if (value !== undefined)
            reflectionMergePartial<JobDirective>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JobDirective): JobDirective {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string job_id */ 1:
                    message.jobId = reader.string();
                    break;
                case /* jobs_registry.JobControlAction action */ 2:
                    message.action = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JobDirective, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string job_id = 1; */
        if (message.jobId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jobId);
        /* jobs_registry.JobControlAction action = 2; */
        if (message.action !== 0)
            writer.tag(2, WireType.Varint).int32(message.action);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.JobDirective
 */
export const JobDirective = new JobDirective$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ControlResponse$Type extends MessageType<ControlResponse> {
    constructor() {
        super("jobs_registry.ControlResponse", [
            { no: 1, name: "directives", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => JobDirective },
            { no: 2, name: "max_concurrency", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "dispatch_paused", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ControlResponse>): ControlResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.directives = [];
        message.maxConcurrency = 0;
        message.dispatchPaused = false;
        if (value !== undefined)
            reflectionMergePartial<ControlResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ControlResponse): ControlResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated jobs_registry.JobDirective directives */ 1:
                    message.directives.push(JobDirective.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 max_concurrency */ 2:
                    message.maxConcurrency = reader.int32();
                    break;
                case /* bool dispatch_paused */ 3:
                    message.dispatchPaused = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ControlResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated jobs_registry.JobDirective directives = 1; */
        for (let i = 0; i < message.directives.length; i++)
            JobDirective.internalBinaryWrite(message.directives[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 max_concurrency = 2; */
        if (message.maxConcurrency !== 0)
            writer.tag(2, WireType.Varint).int32(message.maxConcurrency);
        /* bool dispatch_paused = 3; */
        if (message.dispatchPaused !== false)
            writer.tag(3, WireType.Varint).bool(message.dispatchPaused);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.ControlResponse
 */
export const ControlResponse = new ControlResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Job$Type extends MessageType<Job> {
    constructor() {
        super("jobs_registry.Job", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "asset", kind: "message", T: () => Asset },
            { no: 3, name: "command", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Job>): Job {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<Job>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Job): Job {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* jobs_registry.Asset asset */ 2:
                    message.asset = Asset.internalBinaryRead(reader, reader.uint32(), options, message.asset);
                    break;
                case /* optional string command */ 3:
                    message.command = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Job, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* jobs_registry.Asset asset = 2; */
        if (message.asset)
            Asset.internalBinaryWrite(message.asset, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional string command = 3; */
        if (message.command !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.command);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.Job
 */
export const Job = new Job$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JobResponse$Type extends MessageType<JobResponse> {
    constructor() {
        super("jobs_registry.JobResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<JobResponse>): JobResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<JobResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JobResponse): JobResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JobResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.JobResponse
 */
export const JobResponse = new JobResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JobResultRequest$Type extends MessageType<JobResultRequest> {
    constructor() {
        super("jobs_registry.JobResultRequest", [
            { no: 1, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "data", kind: "message", T: () => UpdateResultDto }
        ]);
    }
    create(value?: PartialMessage<JobResultRequest>): JobResultRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerId = "";
        if (value !== undefined)
            reflectionMergePartial<JobResultRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JobResultRequest): JobResultRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_id */ 1:
                    message.workerId = reader.string();
                    break;
                case /* jobs_registry.UpdateResultDto data */ 2:
                    message.data = UpdateResultDto.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JobResultRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_id = 1; */
        if (message.workerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerId);
        /* jobs_registry.UpdateResultDto data = 2; */
        if (message.data)
            UpdateResultDto.internalBinaryWrite(message.data, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.JobResultRequest
 */
export const JobResultRequest = new JobResultRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateResultDto$Type extends MessageType<UpdateResultDto> {
    constructor() {
        super("jobs_registry.UpdateResultDto", [
            { no: 1, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "data", kind: "message", T: () => DataPayloadResult }
        ]);
    }
    create(value?: PartialMessage<UpdateResultDto>): UpdateResultDto {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateResultDto>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateResultDto): UpdateResultDto {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string job_id */ 1:
                    message.jobId = reader.string();
                    break;
                case /* jobs_registry.DataPayloadResult data */ 2:
                    message.data = DataPayloadResult.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateResultDto, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string job_id = 1; */
        if (message.jobId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jobId);
        /* jobs_registry.DataPayloadResult data = 2; */
        if (message.data)
            DataPayloadResult.internalBinaryWrite(message.data, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.UpdateResultDto
 */
export const UpdateResultDto = new UpdateResultDto$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataPayloadResult$Type extends MessageType<DataPayloadResult> {
    constructor() {
        super("jobs_registry.DataPayloadResult", [
            { no: 1, name: "error", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "raw", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "assets", kind: "message", oneof: "payload", T: () => AssetList },
            { no: 4, name: "http_response", kind: "message", oneof: "payload", T: () => HttpResponse },
            { no: 5, name: "numbers", kind: "message", oneof: "payload", T: () => NumberList },
            { no: 6, name: "vulnerabilities", kind: "message", oneof: "payload", T: () => VulnerabilityList },
            { no: 7, name: "asset_tags", kind: "message", oneof: "payload", T: () => AssetTagList }
        ]);
    }
    create(value?: PartialMessage<DataPayloadResult>): DataPayloadResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.error = false;
        message.payload = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<DataPayloadResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DataPayloadResult): DataPayloadResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool error */ 1:
                    message.error = reader.bool();
                    break;
                case /* optional string raw */ 2:
                    message.raw = reader.string();
                    break;
                case /* jobs_registry.AssetList assets */ 3:
                    message.payload = {
                        oneofKind: "assets",
                        assets: AssetList.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).assets)
                    };
                    break;
                case /* jobs_registry.HttpResponse http_response */ 4:
                    message.payload = {
                        oneofKind: "httpResponse",
                        httpResponse: HttpResponse.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).httpResponse)
                    };
                    break;
                case /* jobs_registry.NumberList numbers */ 5:
                    message.payload = {
                        oneofKind: "numbers",
                        numbers: NumberList.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).numbers)
                    };
                    break;
                case /* jobs_registry.VulnerabilityList vulnerabilities */ 6:
                    message.payload = {
                        oneofKind: "vulnerabilities",
                        vulnerabilities: VulnerabilityList.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).vulnerabilities)
                    };
                    break;
                case /* jobs_registry.AssetTagList asset_tags */ 7:
                    message.payload = {
                        oneofKind: "assetTags",
                        assetTags: AssetTagList.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).assetTags)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DataPayloadResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool error = 1; */
        if (message.error !== false)
            writer.tag(1, WireType.Varint).bool(message.error);
        /* optional string raw = 2; */
        if (message.raw !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.raw);
        /* jobs_registry.AssetList assets = 3; */
        if (message.payload.oneofKind === "assets")
            AssetList.internalBinaryWrite(message.payload.assets, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* jobs_registry.HttpResponse http_response = 4; */
        if (message.payload.oneofKind === "httpResponse")
            HttpResponse.internalBinaryWrite(message.payload.httpResponse, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* jobs_registry.NumberList numbers = 5; */
        if (message.payload.oneofKind === "numbers")
            NumberList.internalBinaryWrite(message.payload.numbers, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* jobs_registry.VulnerabilityList vulnerabilities = 6; */
        if (message.payload.oneofKind === "vulnerabilities")
            VulnerabilityList.internalBinaryWrite(message.payload.vulnerabilities, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* jobs_registry.AssetTagList asset_tags = 7; */
        if (message.payload.oneofKind === "assetTags")
            AssetTagList.internalBinaryWrite(message.payload.assetTags, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.DataPayloadResult
 */
export const DataPayloadResult = new DataPayloadResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AssetList$Type extends MessageType<AssetList> {
    constructor() {
        super("jobs_registry.AssetList", [
            { no: 1, name: "values", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Asset }
        ]);
    }
    create(value?: PartialMessage<AssetList>): AssetList {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<AssetList>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AssetList): AssetList {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated jobs_registry.Asset values */ 1:
                    message.values.push(Asset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AssetList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated jobs_registry.Asset values = 1; */
        for (let i = 0; i < message.values.length; i++)
            Asset.internalBinaryWrite(message.values[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.AssetList
 */
export const AssetList = new AssetList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NumberList$Type extends MessageType<NumberList> {
    constructor() {
        super("jobs_registry.NumberList", [
            { no: 1, name: "values", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<NumberList>): NumberList {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<NumberList>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NumberList): NumberList {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int32 values */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.values.push(reader.int32());
                    else
                        message.values.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NumberList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated int32 values = 1; */
        if (message.values.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.values.length; i++)
                writer.int32(message.values[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.NumberList
 */
export const NumberList = new NumberList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VulnerabilityList$Type extends MessageType<VulnerabilityList> {
    constructor() {
        super("jobs_registry.VulnerabilityList", [
            { no: 1, name: "values", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Vulnerability }
        ]);
    }
    create(value?: PartialMessage<VulnerabilityList>): VulnerabilityList {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<VulnerabilityList>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VulnerabilityList): VulnerabilityList {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated jobs_registry.Vulnerability values */ 1:
                    message.values.push(Vulnerability.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VulnerabilityList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated jobs_registry.Vulnerability values = 1; */
        for (let i = 0; i < message.values.length; i++)
            Vulnerability.internalBinaryWrite(message.values[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.VulnerabilityList
 */
export const VulnerabilityList = new VulnerabilityList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AssetTagList$Type extends MessageType<AssetTagList> {
    constructor() {
        super("jobs_registry.AssetTagList", [
            { no: 1, name: "values", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AssetTag }
        ]);
    }
    create(value?: PartialMessage<AssetTagList>): AssetTagList {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = [];
        if (value !== undefined)
            reflectionMergePartial<AssetTagList>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AssetTagList): AssetTagList {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated jobs_registry.AssetTag values */ 1:
                    message.values.push(AssetTag.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AssetTagList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated jobs_registry.AssetTag values = 1; */
        for (let i = 0; i < message.values.length; i++)
            AssetTag.internalBinaryWrite(message.values[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.AssetTagList
 */
export const AssetTagList = new AssetTagList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Asset$Type extends MessageType<Asset> {
    constructor() {
        super("jobs_registry.Asset", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "target_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "is_primary", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "dns_records", kind: "message", T: () => Struct },
            { no: 8, name: "is_enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Asset>): Asset {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.value = "";
        message.targetId = "";
        message.isPrimary = false;
        message.isEnabled = false;
        if (value !== undefined)
            reflectionMergePartial<Asset>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Asset): Asset {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 3:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* string value */ 4:
                    message.value = reader.string();
                    break;
                case /* string target_id */ 5:
                    message.targetId = reader.string();
                    break;
                case /* bool is_primary */ 6:
                    message.isPrimary = reader.bool();
                    break;
                case /* google.protobuf.Struct dns_records */ 7:
                    message.dnsRecords = Struct.internalBinaryRead(reader, reader.uint32(), options, message.dnsRecords);
                    break;
                case /* bool is_enabled */ 8:
                    message.isEnabled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Asset, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 3; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string value = 4; */
        if (message.value !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.value);
        /* string target_id = 5; */
        if (message.targetId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.targetId);
        /* bool is_primary = 6; */
        if (message.isPrimary !== false)
            writer.tag(6, WireType.Varint).bool(message.isPrimary);
        /* google.protobuf.Struct dns_records = 7; */
        if (message.dnsRecords)
            Struct.internalBinaryWrite(message.dnsRecords, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* bool is_enabled = 8; */
        if (message.isEnabled !== false)
            writer.tag(8, WireType.Varint).bool(message.isEnabled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.Asset
 */
export const Asset = new Asset$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HttpResponse$Type extends MessageType<HttpResponse> {
    constructor() {
        super("jobs_registry.HttpResponse", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "timestamp", kind: "message", T: () => Timestamp },
            { no: 4, name: "tls", kind: "message", T: () => Struct },
            { no: 5, name: "port", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "input", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "scheme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "webserver", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "body", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "content_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "method", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 16, name: "favicon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 17, name: "favicon_md5", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "favicon_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "header", kind: "message", T: () => Struct },
            { no: 20, name: "raw_header", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "request", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "time", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "a", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "tech", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "words", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 26, name: "lines", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 27, name: "status_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 28, name: "content_length", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 29, name: "failed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 30, name: "knowledgebase", kind: "message", T: () => Struct },
            { no: 31, name: "resolvers", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 32, name: "chain_status_codes", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "asset_service_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 34, name: "job_history_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HttpResponse>): HttpResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.port = "";
        message.url = "";
        message.input = "";
        message.title = "";
        message.scheme = "";
        message.webserver = "";
        message.body = "";
        message.contentType = "";
        message.method = "";
        message.host = "";
        message.path = "";
        message.favicon = "";
        message.faviconMd5 = "";
        message.faviconUrl = "";
        message.rawHeader = "";
        message.request = "";
        message.time = "";
        message.a = [];
        message.tech = [];
        message.words = 0;
        message.lines = 0;
        message.statusCode = 0;
        message.contentLength = 0;
        message.failed = false;
        message.resolvers = [];
        message.chainStatusCodes = [];
        message.assetServiceId = "";
        message.jobHistoryId = "";
        if (value !== undefined)
            reflectionMergePartial<HttpResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HttpResponse): HttpResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* google.protobuf.Timestamp created_at */ 2:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp timestamp */ 3:
                    message.timestamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.timestamp);
                    break;
                case /* google.protobuf.Struct tls */ 4:
                    message.tls = Struct.internalBinaryRead(reader, reader.uint32(), options, message.tls);
                    break;
                case /* string port */ 5:
                    message.port = reader.string();
                    break;
                case /* string url */ 6:
                    message.url = reader.string();
                    break;
                case /* string input */ 7:
                    message.input = reader.string();
                    break;
                case /* string title */ 8:
                    message.title = reader.string();
                    break;
                case /* string scheme */ 9:
                    message.scheme = reader.string();
                    break;
                case /* string webserver */ 10:
                    message.webserver = reader.string();
                    break;
                case /* string body */ 11:
                    message.body = reader.string();
                    break;
                case /* string content_type */ 12:
                    message.contentType = reader.string();
                    break;
                case /* string method */ 13:
                    message.method = reader.string();
                    break;
                case /* string host */ 14:
                    message.host = reader.string();
                    break;
                case /* string path */ 15:
                    message.path = reader.string();
                    break;
                case /* string favicon */ 16:
                    message.favicon = reader.string();
                    break;
                case /* string favicon_md5 */ 17:
                    message.faviconMd5 = reader.string();
                    break;
                case /* string favicon_url */ 18:
                    message.faviconUrl = reader.string();
                    break;
                case /* google.protobuf.Struct header */ 19:
                    message.header = Struct.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string raw_header */ 20:
                    message.rawHeader = reader.string();
                    break;
                case /* string request */ 21:
                    message.request = reader.string();
                    break;
                case /* string time */ 22:
                    message.time = reader.string();
                    break;
                case /* repeated string a */ 23:
                    message.a.push(reader.string());
                    break;
                case /* repeated string tech */ 24:
                    message.tech.push(reader.string());
                    break;
                case /* int32 words */ 25:
                    message.words = reader.int32();
                    break;
                case /* int32 lines */ 26:
                    message.lines = reader.int32();
                    break;
                case /* int32 status_code */ 27:
                    message.statusCode = reader.int32();
                    break;
                case /* int32 content_length */ 28:
                    message.contentLength = reader.int32();
                    break;
                case /* bool failed */ 29:
                    message.failed = reader.bool();
                    break;
                case /* google.protobuf.Struct knowledgebase */ 30:
                    message.knowledgebase = Struct.internalBinaryRead(reader, reader.uint32(), options, message.knowledgebase);
                    break;
                case /* repeated string resolvers */ 31:
                    message.resolvers.push(reader.string());
                    break;
                case /* repeated string chain_status_codes */ 32:
                    message.chainStatusCodes.push(reader.string());
                    break;
                case /* string asset_service_id */ 33:
                    message.assetServiceId = reader.string();
                    break;
                case /* string job_history_id */ 34:
                    message.jobHistoryId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HttpResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* google.protobuf.Timestamp created_at = 2; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp timestamp = 3; */
        if (message.timestamp)
            Timestamp.internalBinaryWrite(message.timestamp, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Struct tls = 4; */
        if (message.tls)
            Struct.internalBinaryWrite(message.tls, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string port = 5; */
        if (message.port !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.port);
        /* string url = 6; */
        if (message.url !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.url);
        /* string input = 7; */
        if (message.input !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.input);
        /* string title = 8; */
        if (message.title !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.title);
        /* string scheme = 9; */
        if (message.scheme !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.scheme);
        /* string webserver = 10; */
        if (message.webserver !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.webserver);
        /* string body = 11; */
        if (message.body !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.body);
        /* string content_type = 12; */
        if (message.contentType !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.contentType);
        /* string method = 13; */
        if (message.method !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.method);
        /* string host = 14; */
        if (message.host !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.host);
        /* string path = 15; */
        if (message.path !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.path);
        /* string favicon = 16; */
        if (message.favicon !== "")
            writer.tag(16, WireType.LengthDelimited).string(message.favicon);
        /* string favicon_md5 = 17; */
        if (message.faviconMd5 !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.faviconMd5);
        /* string favicon_url = 18; */
        if (message.faviconUrl !== "")
            writer.tag(18, WireType.LengthDelimited).string(message.faviconUrl);
        /* google.protobuf.Struct header = 19; */
        if (message.header)
            Struct.internalBinaryWrite(message.header, writer.tag(19, WireType.LengthDelimited).fork(), options).join();
        /* string raw_header = 20; */
        if (message.rawHeader !== "")
            writer.tag(20, WireType.LengthDelimited).string(message.rawHeader);
        /* string request = 21; */
        if (message.request !== "")
            writer.tag(21, WireType.LengthDelimited).string(message.request);
        /* string time = 22; */
        if (message.time !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.time);
        /* repeated string a = 23; */
        for (let i = 0; i < message.a.length; i++)
            writer.tag(23, WireType.LengthDelimited).string(message.a[i]);
        /* repeated string tech = 24; */
        for (let i = 0; i < message.tech.length; i++)
            writer.tag(24, WireType.LengthDelimited).string(message.tech[i]);
        /* int32 words = 25; */
        if (message.words !== 0)
            writer.tag(25, WireType.Varint).int32(message.words);
        /* int32 lines = 26; */
        if (message.lines !== 0)
            writer.tag(26, WireType.Varint).int32(message.lines);
        /* int32 status_code = 27; */
        if (message.statusCode !== 0)
            writer.tag(27, WireType.Varint).int32(message.statusCode);
        /* int32 content_length = 28; */
        if (message.contentLength !== 0)
            writer.tag(28, WireType.Varint).int32(message.contentLength);
        /* bool failed = 29; */
        if (message.failed !== false)
            writer.tag(29, WireType.Varint).bool(message.failed);
        /* google.protobuf.Struct knowledgebase = 30; */
        if (message.knowledgebase)
            Struct.internalBinaryWrite(message.knowledgebase, writer.tag(30, WireType.LengthDelimited).fork(), options).join();
        /* repeated string resolvers = 31; */
        for (let i = 0; i < message.resolvers.length; i++)
            writer.tag(31, WireType.LengthDelimited).string(message.resolvers[i]);
        /* repeated string chain_status_codes = 32; */
        for (let i = 0; i < message.chainStatusCodes.length; i++)
            writer.tag(32, WireType.LengthDelimited).string(message.chainStatusCodes[i]);
        /* string asset_service_id = 33; */
        if (message.assetServiceId !== "")
            writer.tag(33, WireType.LengthDelimited).string(message.assetServiceId);
        /* string job_history_id = 34; */
        if (message.jobHistoryId !== "")
            writer.tag(34, WireType.LengthDelimited).string(message.jobHistoryId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.HttpResponse
 */
export const HttpResponse = new HttpResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Vulnerability$Type extends MessageType<Vulnerability> {
    constructor() {
        super("jobs_registry.Vulnerability", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "synopsis", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "severity", kind: "enum", T: () => ["jobs_registry.Severity", Severity] },
            { no: 6, name: "tags", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "references", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "authors", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "affected_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "ip_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "host", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "ports", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "cvss_metric", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "cvss_score", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 15, name: "epss_score", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 16, name: "vpr_score", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 17, name: "cve_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "bid_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 19, name: "cwe_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 20, name: "cea_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 21, name: "iava", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 22, name: "cve_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 23, name: "cwe_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 24, name: "solution", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 25, name: "extractor_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 26, name: "extracted_results", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 27, name: "publication_date", kind: "message", T: () => Timestamp },
            { no: 28, name: "modification_date", kind: "message", T: () => Timestamp },
            { no: 29, name: "tool_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 30, name: "asset_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 31, name: "file_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 32, name: "job_history_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "is_archived", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 34, name: "fingerprint", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Vulnerability>): Vulnerability {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        message.synopsis = "";
        message.severity = 0;
        message.tags = [];
        message.references = [];
        message.authors = [];
        message.affectedUrl = "";
        message.ipAddress = "";
        message.host = "";
        message.ports = [];
        message.cvssMetric = "";
        message.cvssScore = 0;
        message.epssScore = 0;
        message.vprScore = 0;
        message.cveId = [];
        message.bidId = [];
        message.cweId = [];
        message.ceaId = [];
        message.iava = [];
        message.cveUrl = "";
        message.cweUrl = "";
        message.solution = "";
        message.extractorName = "";
        message.extractedResults = [];
        message.toolId = "";
        message.assetId = "";
        message.filePath = "";
        message.jobHistoryId = "";
        message.isArchived = false;
        message.fingerprint = "";
        if (value !== undefined)
            reflectionMergePartial<Vulnerability>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Vulnerability): Vulnerability {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string synopsis */ 4:
                    message.synopsis = reader.string();
                    break;
                case /* jobs_registry.Severity severity */ 5:
                    message.severity = reader.int32();
                    break;
                case /* repeated string tags */ 6:
                    message.tags.push(reader.string());
                    break;
                case /* repeated string references */ 7:
                    message.references.push(reader.string());
                    break;
                case /* repeated string authors */ 8:
                    message.authors.push(reader.string());
                    break;
                case /* string affected_url */ 9:
                    message.affectedUrl = reader.string();
                    break;
                case /* string ip_address */ 10:
                    message.ipAddress = reader.string();
                    break;
                case /* string host */ 11:
                    message.host = reader.string();
                    break;
                case /* repeated string ports */ 12:
                    message.ports.push(reader.string());
                    break;
                case /* string cvss_metric */ 13:
                    message.cvssMetric = reader.string();
                    break;
                case /* float cvss_score */ 14:
                    message.cvssScore = reader.float();
                    break;
                case /* float epss_score */ 15:
                    message.epssScore = reader.float();
                    break;
                case /* float vpr_score */ 16:
                    message.vprScore = reader.float();
                    break;
                case /* repeated string cve_id */ 17:
                    message.cveId.push(reader.string());
                    break;
                case /* repeated string bid_id */ 18:
                    message.bidId.push(reader.string());
                    break;
                case /* repeated string cwe_id */ 19:
                    message.cweId.push(reader.string());
                    break;
                case /* repeated string cea_id */ 20:
                    message.ceaId.push(reader.string());
                    break;
                case /* repeated string iava */ 21:
                    message.iava.push(reader.string());
                    break;
                case /* string cve_url */ 22:
                    message.cveUrl = reader.string();
                    break;
                case /* string cwe_url */ 23:
                    message.cweUrl = reader.string();
                    break;
                case /* string solution */ 24:
                    message.solution = reader.string();
                    break;
                case /* string extractor_name */ 25:
                    message.extractorName = reader.string();
                    break;
                case /* repeated string extracted_results */ 26:
                    message.extractedResults.push(reader.string());
                    break;
                case /* google.protobuf.Timestamp publication_date */ 27:
                    message.publicationDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publicationDate);
                    break;
                case /* google.protobuf.Timestamp modification_date */ 28:
                    message.modificationDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.modificationDate);
                    break;
                case /* string tool_id */ 29:
                    message.toolId = reader.string();
                    break;
                case /* string asset_id */ 30:
                    message.assetId = reader.string();
                    break;
                case /* string file_path */ 31:
                    message.filePath = reader.string();
                    break;
                case /* string job_history_id */ 32:
                    message.jobHistoryId = reader.string();
                    break;
                case /* bool is_archived */ 33:
                    message.isArchived = reader.bool();
                    break;
                case /* string fingerprint */ 34:
                    message.fingerprint = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Vulnerability, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string synopsis = 4; */
        if (message.synopsis !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.synopsis);
        /* jobs_registry.Severity severity = 5; */
        if (message.severity !== 0)
            writer.tag(5, WireType.Varint).int32(message.severity);
        /* repeated string tags = 6; */
        for (let i = 0; i < message.tags.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.tags[i]);
        /* repeated string references = 7; */
        for (let i = 0; i < message.references.length; i++)
            writer.tag(7, WireType.LengthDelimited).string(message.references[i]);
        /* repeated string authors = 8; */
        for (let i = 0; i < message.authors.length; i++)
            writer.tag(8, WireType.LengthDelimited).string(message.authors[i]);
        /* string affected_url = 9; */
        if (message.affectedUrl !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.affectedUrl);
        /* string ip_address = 10; */
        if (message.ipAddress !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.ipAddress);
        /* string host = 11; */
        if (message.host !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.host);
        /* repeated string ports = 12; */
        for (let i = 0; i < message.ports.length; i++)
            writer.tag(12, WireType.LengthDelimited).string(message.ports[i]);
        /* string cvss_metric = 13; */
        if (message.cvssMetric !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.cvssMetric);
        /* float cvss_score = 14; */
        if (message.cvssScore !== 0)
            writer.tag(14, WireType.Bit32).float(message.cvssScore);
        /* float epss_score = 15; */
        if (message.epssScore !== 0)
            writer.tag(15, WireType.Bit32).float(message.epssScore);
        /* float vpr_score = 16; */
        if (message.vprScore !== 0)
            writer.tag(16, WireType.Bit32).float(message.vprScore);
        /* repeated string cve_id = 17; */
        for (let i = 0; i < message.cveId.length; i++)
            writer.tag(17, WireType.LengthDelimited).string(message.cveId[i]);
        /* repeated string bid_id = 18; */
        for (let i = 0; i < message.bidId.length; i++)
            writer.tag(18, WireType.LengthDelimited).string(message.bidId[i]);
        /* repeated string cwe_id = 19; */
        for (let i = 0; i < message.cweId.length; i++)
            writer.tag(19, WireType.LengthDelimited).string(message.cweId[i]);
        /* repeated string cea_id = 20; */
        for (let i = 0; i < message.ceaId.length; i++)
            writer.tag(20, WireType.LengthDelimited).string(message.ceaId[i]);
        /* repeated string iava = 21; */
        for (let i = 0; i < message.iava.length; i++)
            writer.tag(21, WireType.LengthDelimited).string(message.iava[i]);
        /* string cve_url = 22; */
        if (message.cveUrl !== "")
            writer.tag(22, WireType.LengthDelimited).string(message.cveUrl);
        /* string cwe_url = 23; */
        if (message.cweUrl !== "")
            writer.tag(23, WireType.LengthDelimited).string(message.cweUrl);
        /* string solution = 24; */
        if (message.solution !== "")
            writer.tag(24, WireType.LengthDelimited).string(message.solution);
        /* string extractor_name = 25; */
        if (message.extractorName !== "")
            writer.tag(25, WireType.LengthDelimited).string(message.extractorName);
        /* repeated string extracted_results = 26; */
        for (let i = 0; i < message.extractedResults.length; i++)
            writer.tag(26, WireType.LengthDelimited).string(message.extractedResults[i]);
        /* google.protobuf.Timestamp publication_date = 27; */
        if (message.publicationDate)
            Timestamp.internalBinaryWrite(message.publicationDate, writer.tag(27, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp modification_date = 28; */
        if (message.modificationDate)
            Timestamp.internalBinaryWrite(message.modificationDate, writer.tag(28, WireType.LengthDelimited).fork(), options).join();
        /* string tool_id = 29; */
        if (message.toolId !== "")
            writer.tag(29, WireType.LengthDelimited).string(message.toolId);
        /* string asset_id = 30; */
        if (message.assetId !== "")
            writer.tag(30, WireType.LengthDelimited).string(message.assetId);
        /* string file_path = 31; */
        if (message.filePath !== "")
            writer.tag(31, WireType.LengthDelimited).string(message.filePath);
        /* string job_history_id = 32; */
        if (message.jobHistoryId !== "")
            writer.tag(32, WireType.LengthDelimited).string(message.jobHistoryId);
        /* bool is_archived = 33; */
        if (message.isArchived !== false)
            writer.tag(33, WireType.Varint).bool(message.isArchived);
        /* string fingerprint = 34; */
        if (message.fingerprint !== "")
            writer.tag(34, WireType.LengthDelimited).string(message.fingerprint);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.Vulnerability
 */
export const Vulnerability = new Vulnerability$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AssetTag$Type extends MessageType<AssetTag> {
    constructor() {
        super("jobs_registry.AssetTag", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tag", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "asset_service_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tool_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AssetTag>): AssetTag {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.tag = "";
        message.assetServiceId = "";
        message.toolId = "";
        if (value !== undefined)
            reflectionMergePartial<AssetTag>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AssetTag): AssetTag {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string tag */ 2:
                    message.tag = reader.string();
                    break;
                case /* string asset_service_id */ 3:
                    message.assetServiceId = reader.string();
                    break;
                case /* string tool_id */ 4:
                    message.toolId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AssetTag, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string tag = 2; */
        if (message.tag !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tag);
        /* string asset_service_id = 3; */
        if (message.assetServiceId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.assetServiceId);
        /* string tool_id = 4; */
        if (message.toolId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.toolId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message jobs_registry.AssetTag
 */
export const AssetTag = new AssetTag$Type();
/**
 * @generated ServiceType for protobuf service jobs_registry.JobsRegistryService
 */
export const JobsRegistryService = new ServiceType("jobs_registry.JobsRegistryService", [
    { name: "Next", options: {}, I: Worker, O: Job },
    { name: "Result", options: {}, I: JobResultRequest, O: JobResponse },
    { name: "Control", options: {}, I: ControlRequest, O: ControlResponse }
]);
