// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "workers.proto" (package "workers", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { WorkersService } from "./workers";
import type { RemoteExecuteResultAck } from "./workers";
import type { RemoteExecuteResultStream } from "./workers";
import type { RemoteExecuteSubscribeResponse } from "./workers";
import type { RemoteExecuteSubscribeRequest } from "./workers";
import type { BuiltinToolRegistryResponse } from "./workers";
import type { BuiltinToolRegistryRequest } from "./workers";
import type { ConnectInternalNetworkResponse } from "./workers";
import type { ConnectInternalNetworkRequest } from "./workers";
import type { StorageResponse } from "./workers";
import type { StorageRequest } from "./workers";
import type { GetManifestResponse } from "./workers";
import type { GetManifestRequest } from "./workers";
import type { AliveResponse } from "./workers";
import type { AliveRequest } from "./workers";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { JoinResponse } from "./workers";
import type { JoinRequest } from "./workers";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service workers.WorkersService
 */
export interface IWorkersServiceClient {
    /**
     * @generated from protobuf rpc: Join
     */
    join(input: JoinRequest, options?: RpcOptions): UnaryCall<JoinRequest, JoinResponse>;
    /**
     * @generated from protobuf rpc: Alive
     */
    alive(input: AliveRequest, options?: RpcOptions): ServerStreamingCall<AliveRequest, AliveResponse>;
    /**
     * @generated from protobuf rpc: GetManifest
     */
    getManifest(input: GetManifestRequest, options?: RpcOptions): UnaryCall<GetManifestRequest, GetManifestResponse>;
    /**
     * @generated from protobuf rpc: Storage
     */
    storage(input: StorageRequest, options?: RpcOptions): ServerStreamingCall<StorageRequest, StorageResponse>;
    /**
     * @generated from protobuf rpc: ConnectInternalNetwork
     */
    connectInternalNetwork(input: ConnectInternalNetworkRequest, options?: RpcOptions): UnaryCall<ConnectInternalNetworkRequest, ConnectInternalNetworkResponse>;
    /**
     * @generated from protobuf rpc: BuiltinToolRegistry
     */
    builtinToolRegistry(input: BuiltinToolRegistryRequest, options?: RpcOptions): UnaryCall<BuiltinToolRegistryRequest, BuiltinToolRegistryResponse>;
    /**
     * @generated from protobuf rpc: RemoteExecuteSubscribe
     */
    remoteExecuteSubscribe(input: RemoteExecuteSubscribeRequest, options?: RpcOptions): ServerStreamingCall<RemoteExecuteSubscribeRequest, RemoteExecuteSubscribeResponse>;
    /**
     * @generated from protobuf rpc: RemoteExecuteResult
     */
    remoteExecuteResult(input: RemoteExecuteResultStream, options?: RpcOptions): UnaryCall<RemoteExecuteResultStream, RemoteExecuteResultAck>;
}
/**
 * @generated from protobuf service workers.WorkersService
 */
export class WorkersServiceClient implements IWorkersServiceClient, ServiceInfo {
    typeName = WorkersService.typeName;
    methods = WorkersService.methods;
    options = WorkersService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Join
     */
    join(input: JoinRequest, options?: RpcOptions): UnaryCall<JoinRequest, JoinResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<JoinRequest, JoinResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Alive
     */
    alive(input: AliveRequest, options?: RpcOptions): ServerStreamingCall<AliveRequest, AliveResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AliveRequest, AliveResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetManifest
     */
    getManifest(input: GetManifestRequest, options?: RpcOptions): UnaryCall<GetManifestRequest, GetManifestResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetManifestRequest, GetManifestResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Storage
     */
    storage(input: StorageRequest, options?: RpcOptions): ServerStreamingCall<StorageRequest, StorageResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<StorageRequest, StorageResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ConnectInternalNetwork
     */
    connectInternalNetwork(input: ConnectInternalNetworkRequest, options?: RpcOptions): UnaryCall<ConnectInternalNetworkRequest, ConnectInternalNetworkResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConnectInternalNetworkRequest, ConnectInternalNetworkResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BuiltinToolRegistry
     */
    builtinToolRegistry(input: BuiltinToolRegistryRequest, options?: RpcOptions): UnaryCall<BuiltinToolRegistryRequest, BuiltinToolRegistryResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<BuiltinToolRegistryRequest, BuiltinToolRegistryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoteExecuteSubscribe
     */
    remoteExecuteSubscribe(input: RemoteExecuteSubscribeRequest, options?: RpcOptions): ServerStreamingCall<RemoteExecuteSubscribeRequest, RemoteExecuteSubscribeResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoteExecuteSubscribeRequest, RemoteExecuteSubscribeResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoteExecuteResult
     */
    remoteExecuteResult(input: RemoteExecuteResultStream, options?: RpcOptions): UnaryCall<RemoteExecuteResultStream, RemoteExecuteResultAck> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoteExecuteResultStream, RemoteExecuteResultAck>("unary", this._transport, method, opt, input);
    }
}
