// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "workers.proto" (package "workers", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message workers.JoinRequest
 */
export interface JoinRequest {
    /**
     * @generated from protobuf field: string api_key = 1
     */
    apiKey: string;
    /**
     * @generated from protobuf field: optional string token = 3
     */
    token?: string;
    /**
     * @generated from protobuf field: optional workers.WorkerMetadata metadata = 4
     */
    metadata?: WorkerMetadata;
}
/**
 * @generated from protobuf message workers.WorkerMetadata
 */
export interface WorkerMetadata {
    /**
     * @generated from protobuf field: optional string name = 1
     */
    name?: string;
    /**
     * @generated from protobuf field: optional string os = 2
     */
    os?: string;
}
/**
 * @generated from protobuf message workers.JoinResponse
 */
export interface JoinResponse {
    /**
     * @generated from protobuf field: string worker_id = 1
     */
    workerId: string;
    /**
     * @generated from protobuf field: string worker_token = 2
     */
    workerToken: string;
}
/**
 * @generated from protobuf message workers.AliveRequest
 */
export interface AliveRequest {
    /**
     * @generated from protobuf field: string worker_token = 1
     */
    workerToken: string;
}
/**
 * @generated from protobuf message workers.AliveResponse
 */
export interface AliveResponse {
    /**
     * @generated from protobuf field: bool alive = 1
     */
    alive: boolean;
    /**
     * @generated from protobuf field: string last_seen_at = 2
     */
    lastSeenAt: string;
    /**
     * @generated from protobuf field: string worker_id = 3
     */
    workerId: string;
}
/**
 * @generated from protobuf message workers.GetManifestRequest
 */
export interface GetManifestRequest {
}
/**
 * @generated from protobuf message workers.GetManifestResponse
 */
export interface GetManifestResponse {
    /**
     * @generated from protobuf field: repeated string init_commands = 1
     */
    initCommands: string[];
}
/**
 * @generated from protobuf message workers.StorageRequest
 */
export interface StorageRequest {
    /**
     * @generated from protobuf field: string path = 1
     */
    path: string;
}
/**
 * @generated from protobuf message workers.StorageResponse
 */
export interface StorageResponse {
    /**
     * @generated from protobuf field: bytes chunk = 1
     */
    chunk: Uint8Array;
    /**
     * @generated from protobuf field: int32 offset = 2
     */
    offset: number;
    /**
     * @generated from protobuf field: bool eof = 3
     */
    eof: boolean;
}
/**
 * @generated from protobuf message workers.NetworkInterfaceMessage
 */
export interface NetworkInterfaceMessage {
    /**
     * @generated from protobuf field: string interface_name = 1
     */
    interfaceName: string;
    /**
     * @generated from protobuf field: string ip_address = 2
     */
    ipAddress: string;
    /**
     * @generated from protobuf field: string cidr = 3
     */
    cidr: string;
    /**
     * @generated from protobuf field: string gateway_ip = 4
     */
    gatewayIp: string;
    /**
     * @generated from protobuf field: string gateway_mac = 5
     */
    gatewayMac: string;
}
/**
 * @generated from protobuf message workers.ConnectInternalNetworkRequest
 */
export interface ConnectInternalNetworkRequest {
    /**
     * @generated from protobuf field: string worker_id = 1
     */
    workerId: string;
    /**
     * @generated from protobuf field: string network_id = 2
     */
    networkId: string;
    /**
     * @generated from protobuf field: repeated workers.NetworkInterfaceMessage network_interfaces = 3
     */
    networkInterfaces: NetworkInterfaceMessage[];
}
/**
 * @generated from protobuf message workers.ConnectInternalNetworkResponse
 */
export interface ConnectInternalNetworkResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
}
/**
 * @generated from protobuf message workers.BuiltinToolRegistryRequest
 */
export interface BuiltinToolRegistryRequest {
    /**
     * @generated from protobuf field: string os = 1
     */
    os: string; // worker sends: runtime.GOOS (e.g., "linux")
    /**
     * @generated from protobuf field: string arch = 2
     */
    arch: string; // worker sends: runtime.GOARCH (e.g., "arm64")
}
/**
 * @generated from protobuf message workers.BuiltinToolRegistryResponse
 */
export interface BuiltinToolRegistryResponse {
    /**
     * @generated from protobuf field: repeated string tool_paths = 1
     */
    toolPaths: string[];
}
/**
 * @generated from protobuf message workers.ScannerStatusReportRequest
 */
export interface ScannerStatusReportRequest {
    /**
     * @generated from protobuf field: string engine_version = 1
     */
    engineVersion: string;
    /**
     * @generated from protobuf field: string template_version = 2
     */
    templateVersion: string;
    /**
     * @generated from protobuf field: string template_source = 3
     */
    templateSource: string;
    /**
     * @generated from protobuf field: string state = 4
     */
    state: string;
    /**
     * @generated from protobuf field: optional string last_update_attempt_at = 5
     */
    lastUpdateAttemptAt?: string;
    /**
     * @generated from protobuf field: optional string last_update_success_at = 6
     */
    lastUpdateSuccessAt?: string;
    /**
     * @generated from protobuf field: optional string last_validated_at = 7
     */
    lastValidatedAt?: string;
    /**
     * @generated from protobuf field: optional string last_error = 8
     */
    lastError?: string;
}
/**
 * @generated from protobuf message workers.ScannerStatusReportResponse
 */
export interface ScannerStatusReportResponse {
    /**
     * @generated from protobuf field: string message = 1
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class JoinRequest$Type extends MessageType<JoinRequest> {
    constructor() {
        super("workers.JoinRequest", [
            { no: 1, name: "api_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "metadata", kind: "message", T: () => WorkerMetadata }
        ]);
    }
    create(value?: PartialMessage<JoinRequest>): JoinRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.apiKey = "";
        if (value !== undefined)
            reflectionMergePartial<JoinRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinRequest): JoinRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string api_key */ 1:
                    message.apiKey = reader.string();
                    break;
                case /* optional string token */ 3:
                    message.token = reader.string();
                    break;
                case /* optional workers.WorkerMetadata metadata */ 4:
                    message.metadata = WorkerMetadata.internalBinaryRead(reader, reader.uint32(), options, message.metadata);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string api_key = 1; */
        if (message.apiKey !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.apiKey);
        /* optional string token = 3; */
        if (message.token !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.token);
        /* optional workers.WorkerMetadata metadata = 4; */
        if (message.metadata)
            WorkerMetadata.internalBinaryWrite(message.metadata, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.JoinRequest
 */
export const JoinRequest = new JoinRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WorkerMetadata$Type extends MessageType<WorkerMetadata> {
    constructor() {
        super("workers.WorkerMetadata", [
            { no: 1, name: "name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "os", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WorkerMetadata>): WorkerMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<WorkerMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WorkerMetadata): WorkerMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string name */ 1:
                    message.name = reader.string();
                    break;
                case /* optional string os */ 2:
                    message.os = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WorkerMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string name = 1; */
        if (message.name !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* optional string os = 2; */
        if (message.os !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.os);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.WorkerMetadata
 */
export const WorkerMetadata = new WorkerMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinResponse$Type extends MessageType<JoinResponse> {
    constructor() {
        super("workers.JoinResponse", [
            { no: 1, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "worker_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<JoinResponse>): JoinResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerId = "";
        message.workerToken = "";
        if (value !== undefined)
            reflectionMergePartial<JoinResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinResponse): JoinResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_id */ 1:
                    message.workerId = reader.string();
                    break;
                case /* string worker_token */ 2:
                    message.workerToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_id = 1; */
        if (message.workerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerId);
        /* string worker_token = 2; */
        if (message.workerToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.workerToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.JoinResponse
 */
export const JoinResponse = new JoinResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AliveRequest$Type extends MessageType<AliveRequest> {
    constructor() {
        super("workers.AliveRequest", [
            { no: 1, name: "worker_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AliveRequest>): AliveRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerToken = "";
        if (value !== undefined)
            reflectionMergePartial<AliveRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AliveRequest): AliveRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_token */ 1:
                    message.workerToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AliveRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_token = 1; */
        if (message.workerToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.AliveRequest
 */
export const AliveRequest = new AliveRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AliveResponse$Type extends MessageType<AliveResponse> {
    constructor() {
        super("workers.AliveResponse", [
            { no: 1, name: "alive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "last_seen_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AliveResponse>): AliveResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.alive = false;
        message.lastSeenAt = "";
        message.workerId = "";
        if (value !== undefined)
            reflectionMergePartial<AliveResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AliveResponse): AliveResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool alive */ 1:
                    message.alive = reader.bool();
                    break;
                case /* string last_seen_at */ 2:
                    message.lastSeenAt = reader.string();
                    break;
                case /* string worker_id */ 3:
                    message.workerId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AliveResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool alive = 1; */
        if (message.alive !== false)
            writer.tag(1, WireType.Varint).bool(message.alive);
        /* string last_seen_at = 2; */
        if (message.lastSeenAt !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.lastSeenAt);
        /* string worker_id = 3; */
        if (message.workerId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.workerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.AliveResponse
 */
export const AliveResponse = new AliveResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetManifestRequest$Type extends MessageType<GetManifestRequest> {
    constructor() {
        super("workers.GetManifestRequest", []);
    }
    create(value?: PartialMessage<GetManifestRequest>): GetManifestRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetManifestRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetManifestRequest): GetManifestRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetManifestRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.GetManifestRequest
 */
export const GetManifestRequest = new GetManifestRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetManifestResponse$Type extends MessageType<GetManifestResponse> {
    constructor() {
        super("workers.GetManifestResponse", [
            { no: 1, name: "init_commands", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetManifestResponse>): GetManifestResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.initCommands = [];
        if (value !== undefined)
            reflectionMergePartial<GetManifestResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetManifestResponse): GetManifestResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string init_commands */ 1:
                    message.initCommands.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetManifestResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string init_commands = 1; */
        for (let i = 0; i < message.initCommands.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.initCommands[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.GetManifestResponse
 */
export const GetManifestResponse = new GetManifestResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StorageRequest$Type extends MessageType<StorageRequest> {
    constructor() {
        super("workers.StorageRequest", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StorageRequest>): StorageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.path = "";
        if (value !== undefined)
            reflectionMergePartial<StorageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StorageRequest): StorageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string path */ 1:
                    message.path = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StorageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string path = 1; */
        if (message.path !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.path);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.StorageRequest
 */
export const StorageRequest = new StorageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StorageResponse$Type extends MessageType<StorageResponse> {
    constructor() {
        super("workers.StorageResponse", [
            { no: 1, name: "chunk", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "offset", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "eof", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<StorageResponse>): StorageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chunk = new Uint8Array(0);
        message.offset = 0;
        message.eof = false;
        if (value !== undefined)
            reflectionMergePartial<StorageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StorageResponse): StorageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes chunk */ 1:
                    message.chunk = reader.bytes();
                    break;
                case /* int32 offset */ 2:
                    message.offset = reader.int32();
                    break;
                case /* bool eof */ 3:
                    message.eof = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StorageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes chunk = 1; */
        if (message.chunk.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.chunk);
        /* int32 offset = 2; */
        if (message.offset !== 0)
            writer.tag(2, WireType.Varint).int32(message.offset);
        /* bool eof = 3; */
        if (message.eof !== false)
            writer.tag(3, WireType.Varint).bool(message.eof);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.StorageResponse
 */
export const StorageResponse = new StorageResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NetworkInterfaceMessage$Type extends MessageType<NetworkInterfaceMessage> {
    constructor() {
        super("workers.NetworkInterfaceMessage", [
            { no: 1, name: "interface_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "ip_address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "cidr", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "gateway_ip", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "gateway_mac", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NetworkInterfaceMessage>): NetworkInterfaceMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.interfaceName = "";
        message.ipAddress = "";
        message.cidr = "";
        message.gatewayIp = "";
        message.gatewayMac = "";
        if (value !== undefined)
            reflectionMergePartial<NetworkInterfaceMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NetworkInterfaceMessage): NetworkInterfaceMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string interface_name */ 1:
                    message.interfaceName = reader.string();
                    break;
                case /* string ip_address */ 2:
                    message.ipAddress = reader.string();
                    break;
                case /* string cidr */ 3:
                    message.cidr = reader.string();
                    break;
                case /* string gateway_ip */ 4:
                    message.gatewayIp = reader.string();
                    break;
                case /* string gateway_mac */ 5:
                    message.gatewayMac = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NetworkInterfaceMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string interface_name = 1; */
        if (message.interfaceName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.interfaceName);
        /* string ip_address = 2; */
        if (message.ipAddress !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.ipAddress);
        /* string cidr = 3; */
        if (message.cidr !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.cidr);
        /* string gateway_ip = 4; */
        if (message.gatewayIp !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.gatewayIp);
        /* string gateway_mac = 5; */
        if (message.gatewayMac !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.gatewayMac);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.NetworkInterfaceMessage
 */
export const NetworkInterfaceMessage = new NetworkInterfaceMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectInternalNetworkRequest$Type extends MessageType<ConnectInternalNetworkRequest> {
    constructor() {
        super("workers.ConnectInternalNetworkRequest", [
            { no: 1, name: "worker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "network_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "network_interfaces", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => NetworkInterfaceMessage }
        ]);
    }
    create(value?: PartialMessage<ConnectInternalNetworkRequest>): ConnectInternalNetworkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workerId = "";
        message.networkId = "";
        message.networkInterfaces = [];
        if (value !== undefined)
            reflectionMergePartial<ConnectInternalNetworkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectInternalNetworkRequest): ConnectInternalNetworkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string worker_id */ 1:
                    message.workerId = reader.string();
                    break;
                case /* string network_id */ 2:
                    message.networkId = reader.string();
                    break;
                case /* repeated workers.NetworkInterfaceMessage network_interfaces */ 3:
                    message.networkInterfaces.push(NetworkInterfaceMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectInternalNetworkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string worker_id = 1; */
        if (message.workerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workerId);
        /* string network_id = 2; */
        if (message.networkId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.networkId);
        /* repeated workers.NetworkInterfaceMessage network_interfaces = 3; */
        for (let i = 0; i < message.networkInterfaces.length; i++)
            NetworkInterfaceMessage.internalBinaryWrite(message.networkInterfaces[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.ConnectInternalNetworkRequest
 */
export const ConnectInternalNetworkRequest = new ConnectInternalNetworkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectInternalNetworkResponse$Type extends MessageType<ConnectInternalNetworkResponse> {
    constructor() {
        super("workers.ConnectInternalNetworkResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConnectInternalNetworkResponse>): ConnectInternalNetworkResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ConnectInternalNetworkResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectInternalNetworkResponse): ConnectInternalNetworkResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectInternalNetworkResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.ConnectInternalNetworkResponse
 */
export const ConnectInternalNetworkResponse = new ConnectInternalNetworkResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BuiltinToolRegistryRequest$Type extends MessageType<BuiltinToolRegistryRequest> {
    constructor() {
        super("workers.BuiltinToolRegistryRequest", [
            { no: 1, name: "os", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "arch", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BuiltinToolRegistryRequest>): BuiltinToolRegistryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.os = "";
        message.arch = "";
        if (value !== undefined)
            reflectionMergePartial<BuiltinToolRegistryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BuiltinToolRegistryRequest): BuiltinToolRegistryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string os */ 1:
                    message.os = reader.string();
                    break;
                case /* string arch */ 2:
                    message.arch = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BuiltinToolRegistryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string os = 1; */
        if (message.os !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.os);
        /* string arch = 2; */
        if (message.arch !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.arch);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.BuiltinToolRegistryRequest
 */
export const BuiltinToolRegistryRequest = new BuiltinToolRegistryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BuiltinToolRegistryResponse$Type extends MessageType<BuiltinToolRegistryResponse> {
    constructor() {
        super("workers.BuiltinToolRegistryResponse", [
            { no: 1, name: "tool_paths", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BuiltinToolRegistryResponse>): BuiltinToolRegistryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.toolPaths = [];
        if (value !== undefined)
            reflectionMergePartial<BuiltinToolRegistryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BuiltinToolRegistryResponse): BuiltinToolRegistryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string tool_paths */ 1:
                    message.toolPaths.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BuiltinToolRegistryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string tool_paths = 1; */
        for (let i = 0; i < message.toolPaths.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.toolPaths[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.BuiltinToolRegistryResponse
 */
export const BuiltinToolRegistryResponse = new BuiltinToolRegistryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScannerStatusReportRequest$Type extends MessageType<ScannerStatusReportRequest> {
    constructor() {
        super("workers.ScannerStatusReportRequest", [
            { no: 1, name: "engine_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "template_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "template_source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "last_update_attempt_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "last_update_success_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "last_validated_at", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "last_error", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScannerStatusReportRequest>): ScannerStatusReportRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.engineVersion = "";
        message.templateVersion = "";
        message.templateSource = "";
        message.state = "";
        if (value !== undefined)
            reflectionMergePartial<ScannerStatusReportRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScannerStatusReportRequest): ScannerStatusReportRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string engine_version */ 1:
                    message.engineVersion = reader.string();
                    break;
                case /* string template_version */ 2:
                    message.templateVersion = reader.string();
                    break;
                case /* string template_source */ 3:
                    message.templateSource = reader.string();
                    break;
                case /* string state */ 4:
                    message.state = reader.string();
                    break;
                case /* optional string last_update_attempt_at */ 5:
                    message.lastUpdateAttemptAt = reader.string();
                    break;
                case /* optional string last_update_success_at */ 6:
                    message.lastUpdateSuccessAt = reader.string();
                    break;
                case /* optional string last_validated_at */ 7:
                    message.lastValidatedAt = reader.string();
                    break;
                case /* optional string last_error */ 8:
                    message.lastError = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScannerStatusReportRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string engine_version = 1; */
        if (message.engineVersion !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.engineVersion);
        /* string template_version = 2; */
        if (message.templateVersion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.templateVersion);
        /* string template_source = 3; */
        if (message.templateSource !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.templateSource);
        /* string state = 4; */
        if (message.state !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.state);
        /* optional string last_update_attempt_at = 5; */
        if (message.lastUpdateAttemptAt !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.lastUpdateAttemptAt);
        /* optional string last_update_success_at = 6; */
        if (message.lastUpdateSuccessAt !== undefined)
            writer.tag(6, WireType.LengthDelimited).string(message.lastUpdateSuccessAt);
        /* optional string last_validated_at = 7; */
        if (message.lastValidatedAt !== undefined)
            writer.tag(7, WireType.LengthDelimited).string(message.lastValidatedAt);
        /* optional string last_error = 8; */
        if (message.lastError !== undefined)
            writer.tag(8, WireType.LengthDelimited).string(message.lastError);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.ScannerStatusReportRequest
 */
export const ScannerStatusReportRequest = new ScannerStatusReportRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScannerStatusReportResponse$Type extends MessageType<ScannerStatusReportResponse> {
    constructor() {
        super("workers.ScannerStatusReportResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScannerStatusReportResponse>): ScannerStatusReportResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ScannerStatusReportResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScannerStatusReportResponse): ScannerStatusReportResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScannerStatusReportResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message workers.ScannerStatusReportResponse
 */
export const ScannerStatusReportResponse = new ScannerStatusReportResponse$Type();
/**
 * @generated ServiceType for protobuf service workers.WorkersService
 */
export const WorkersService = new ServiceType("workers.WorkersService", [
    { name: "Join", options: {}, I: JoinRequest, O: JoinResponse },
    { name: "Alive", serverStreaming: true, options: {}, I: AliveRequest, O: AliveResponse },
    { name: "GetManifest", options: {}, I: GetManifestRequest, O: GetManifestResponse },
    { name: "Storage", serverStreaming: true, options: {}, I: StorageRequest, O: StorageResponse },
    { name: "ConnectInternalNetwork", options: {}, I: ConnectInternalNetworkRequest, O: ConnectInternalNetworkResponse },
    { name: "BuiltinToolRegistry", options: {}, I: BuiltinToolRegistryRequest, O: BuiltinToolRegistryResponse },
    { name: "ReportScannerStatus", options: {}, I: ScannerStatusReportRequest, O: ScannerStatusReportResponse }
]);
