/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InitAdminRouteImport } from './routes/init-admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as SettingsTabRouteImport } from './routes/settings/$tab'
import { Route as AuthedWorkersRouteImport } from './routes/_authed/workers'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedWorkspacesIndexRouteImport } from './routes/_authed/workspaces/index'
import { Route as AuthedVulnerabilitiesIndexRouteImport } from './routes/_authed/vulnerabilities/index'
import { Route as AuthedToolsIndexRouteImport } from './routes/_authed/tools/index'
import { Route as AuthedTargetsIndexRouteImport } from './routes/_authed/targets/index'
import { Route as AuthedProvidersIndexRouteImport } from './routes/_authed/providers/index'
import { Route as AuthedJobsIndexRouteImport } from './routes/_authed/jobs/index'
import { Route as AuthedIssuesIndexRouteImport } from './routes/_authed/issues/index'
import { Route as AuthedInternalNetworksIndexRouteImport } from './routes/_authed/internal-networks/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedAssetsIndexRouteImport } from './routes/_authed/assets/index'
import { Route as AuthedAgentsIndexRouteImport } from './routes/_authed/agents/index'
import { Route as AuthedWorkspacesCreateRouteImport } from './routes/_authed/workspaces/create'
import { Route as AuthedVulnerabilitiesIdRouteImport } from './routes/_authed/vulnerabilities/$id'
import { Route as AuthedToolsIdRouteImport } from './routes/_authed/tools/$id'
import { Route as AuthedTargetsStartDiscoveryRouteImport } from './routes/_authed/targets/start-discovery'
import { Route as AuthedProvidersCreateRouteImport } from './routes/_authed/providers/create'
import { Route as AuthedIssuesCreateRouteImport } from './routes/_authed/issues/create'
import { Route as AuthedIssuesIdRouteImport } from './routes/_authed/issues/$id'
import { Route as AuthedInternalNetworksCreateRouteImport } from './routes/_authed/internal-networks/create'
import { Route as AuthedInternalNetworksIdRouteImport } from './routes/_authed/internal-networks/$id'
import { Route as AuthedGroupsIdRouteImport } from './routes/_authed/groups/$id'
import { Route as AuthedAssetsIdRouteImport } from './routes/_authed/assets/$id'
import { Route as AuthedAgentsCreateRouteImport } from './routes/_authed/agents/create'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedTargetsIdIndexRouteImport } from './routes/_authed/targets/$id/index'
import { Route as AuthedProvidersIdIndexRouteImport } from './routes/_authed/providers/$id/index'
import { Route as AuthedAgentsConversationsIndexRouteImport } from './routes/_authed/agents/conversations/index'
import { Route as AuthedAgentsIdIndexRouteImport } from './routes/_authed/agents/$id/index'
import { Route as AuthedTargetsIdTabRouteImport } from './routes/_authed/targets/$id/$tab'
import { Route as AuthedProvidersIdEditRouteImport } from './routes/_authed/providers/$id/edit'
import { Route as AuthedJobsRunsIdRouteImport } from './routes/_authed/jobs/runs/$id'
import { Route as AuthedAgentsProvidersConnectRouteImport } from './routes/_authed/agents/providers/connect'
import { Route as AuthedAgentsConversationsConversationIdRouteImport } from './routes/_authed/agents/conversations/$conversationId'
import { Route as AuthedAgentsIdEditRouteImport } from './routes/_authed/agents/$id/edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InitAdminRoute = InitAdminRouteImport.update({
  id: '/init-admin',
  path: '/init-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const SettingsTabRoute = SettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthedWorkersRoute = AuthedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspacesIndexRoute = AuthedWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVulnerabilitiesIndexRoute =
  AuthedVulnerabilitiesIndexRouteImport.update({
    id: '/vulnerabilities/',
    path: '/vulnerabilities/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedToolsIndexRoute = AuthedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTargetsIndexRoute = AuthedTargetsIndexRouteImport.update({
  id: '/targets/',
  path: '/targets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProvidersIndexRoute = AuthedProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIssuesIndexRoute = AuthedIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInternalNetworksIndexRoute =
  AuthedInternalNetworksIndexRouteImport.update({
    id: '/internal-networks/',
    path: '/internal-networks/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssetsIndexRoute = AuthedAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsIndexRoute = AuthedAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspacesCreateRoute = AuthedWorkspacesCreateRouteImport.update({
  id: '/workspaces/create',
  path: '/workspaces/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVulnerabilitiesIdRoute = AuthedVulnerabilitiesIdRouteImport.update({
  id: '/vulnerabilities/$id',
  path: '/vulnerabilities/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedToolsIdRoute = AuthedToolsIdRouteImport.update({
  id: '/tools/$id',
  path: '/tools/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTargetsStartDiscoveryRoute =
  AuthedTargetsStartDiscoveryRouteImport.update({
    id: '/targets/start-discovery',
    path: '/targets/start-discovery',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProvidersCreateRoute = AuthedProvidersCreateRouteImport.update({
  id: '/providers/create',
  path: '/providers/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIssuesCreateRoute = AuthedIssuesCreateRouteImport.update({
  id: '/issues/create',
  path: '/issues/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIssuesIdRoute = AuthedIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInternalNetworksCreateRoute =
  AuthedInternalNetworksCreateRouteImport.update({
    id: '/internal-networks/create',
    path: '/internal-networks/create',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedInternalNetworksIdRoute =
  AuthedInternalNetworksIdRouteImport.update({
    id: '/internal-networks/$id',
    path: '/internal-networks/$id',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdRoute = AuthedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssetsIdRoute = AuthedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsCreateRoute = AuthedAgentsCreateRouteImport.update({
  id: '/agents/create',
  path: '/agents/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTargetsIdIndexRoute = AuthedTargetsIdIndexRouteImport.update({
  id: '/targets/$id/',
  path: '/targets/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProvidersIdIndexRoute = AuthedProvidersIdIndexRouteImport.update({
  id: '/providers/$id/',
  path: '/providers/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsConversationsIndexRoute =
  AuthedAgentsConversationsIndexRouteImport.update({
    id: '/agents/conversations/',
    path: '/agents/conversations/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAgentsIdIndexRoute = AuthedAgentsIdIndexRouteImport.update({
  id: '/agents/$id/',
  path: '/agents/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTargetsIdTabRoute = AuthedTargetsIdTabRouteImport.update({
  id: '/targets/$id/$tab',
  path: '/targets/$id/$tab',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProvidersIdEditRoute = AuthedProvidersIdEditRouteImport.update({
  id: '/providers/$id/edit',
  path: '/providers/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRunsIdRoute = AuthedJobsRunsIdRouteImport.update({
  id: '/jobs/runs/$id',
  path: '/jobs/runs/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsProvidersConnectRoute =
  AuthedAgentsProvidersConnectRouteImport.update({
    id: '/agents/providers/connect',
    path: '/agents/providers/connect',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAgentsConversationsConversationIdRoute =
  AuthedAgentsConversationsConversationIdRouteImport.update({
    id: '/agents/conversations/$conversationId',
    path: '/agents/conversations/$conversationId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAgentsIdEditRoute = AuthedAgentsIdEditRouteImport.update({
  id: '/agents/$id/edit',
  path: '/agents/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AuthedIndexRoute
  '/init-admin': typeof InitAdminRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/notifications': typeof AuthedNotificationsRoute
  '/reports': typeof AuthedReportsRoute
  '/search': typeof AuthedSearchRoute
  '/workers': typeof AuthedWorkersRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/agents/create': typeof AuthedAgentsCreateRoute
  '/assets/$id': typeof AuthedAssetsIdRoute
  '/groups/$id': typeof AuthedGroupsIdRoute
  '/internal-networks/$id': typeof AuthedInternalNetworksIdRoute
  '/internal-networks/create': typeof AuthedInternalNetworksCreateRoute
  '/issues/$id': typeof AuthedIssuesIdRoute
  '/issues/create': typeof AuthedIssuesCreateRoute
  '/providers/create': typeof AuthedProvidersCreateRoute
  '/targets/start-discovery': typeof AuthedTargetsStartDiscoveryRoute
  '/tools/$id': typeof AuthedToolsIdRoute
  '/vulnerabilities/$id': typeof AuthedVulnerabilitiesIdRoute
  '/workspaces/create': typeof AuthedWorkspacesCreateRoute
  '/agents/': typeof AuthedAgentsIndexRoute
  '/assets/': typeof AuthedAssetsIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/internal-networks/': typeof AuthedInternalNetworksIndexRoute
  '/issues/': typeof AuthedIssuesIndexRoute
  '/jobs/': typeof AuthedJobsIndexRoute
  '/providers/': typeof AuthedProvidersIndexRoute
  '/targets/': typeof AuthedTargetsIndexRoute
  '/tools/': typeof AuthedToolsIndexRoute
  '/vulnerabilities/': typeof AuthedVulnerabilitiesIndexRoute
  '/workspaces/': typeof AuthedWorkspacesIndexRoute
  '/agents/$id/edit': typeof AuthedAgentsIdEditRoute
  '/agents/conversations/$conversationId': typeof AuthedAgentsConversationsConversationIdRoute
  '/agents/providers/connect': typeof AuthedAgentsProvidersConnectRoute
  '/jobs/runs/$id': typeof AuthedJobsRunsIdRoute
  '/providers/$id/edit': typeof AuthedProvidersIdEditRoute
  '/targets/$id/$tab': typeof AuthedTargetsIdTabRoute
  '/agents/$id/': typeof AuthedAgentsIdIndexRoute
  '/agents/conversations/': typeof AuthedAgentsConversationsIndexRoute
  '/providers/$id/': typeof AuthedProvidersIdIndexRoute
  '/targets/$id/': typeof AuthedTargetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/init-admin': typeof InitAdminRoute
  '/login': typeof LoginRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/reports': typeof AuthedReportsRoute
  '/search': typeof AuthedSearchRoute
  '/workers': typeof AuthedWorkersRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/': typeof AuthedIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/agents/create': typeof AuthedAgentsCreateRoute
  '/assets/$id': typeof AuthedAssetsIdRoute
  '/groups/$id': typeof AuthedGroupsIdRoute
  '/internal-networks/$id': typeof AuthedInternalNetworksIdRoute
  '/internal-networks/create': typeof AuthedInternalNetworksCreateRoute
  '/issues/$id': typeof AuthedIssuesIdRoute
  '/issues/create': typeof AuthedIssuesCreateRoute
  '/providers/create': typeof AuthedProvidersCreateRoute
  '/targets/start-discovery': typeof AuthedTargetsStartDiscoveryRoute
  '/tools/$id': typeof AuthedToolsIdRoute
  '/vulnerabilities/$id': typeof AuthedVulnerabilitiesIdRoute
  '/workspaces/create': typeof AuthedWorkspacesCreateRoute
  '/agents': typeof AuthedAgentsIndexRoute
  '/assets': typeof AuthedAssetsIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/internal-networks': typeof AuthedInternalNetworksIndexRoute
  '/issues': typeof AuthedIssuesIndexRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/providers': typeof AuthedProvidersIndexRoute
  '/targets': typeof AuthedTargetsIndexRoute
  '/tools': typeof AuthedToolsIndexRoute
  '/vulnerabilities': typeof AuthedVulnerabilitiesIndexRoute
  '/workspaces': typeof AuthedWorkspacesIndexRoute
  '/agents/$id/edit': typeof AuthedAgentsIdEditRoute
  '/agents/conversations/$conversationId': typeof AuthedAgentsConversationsConversationIdRoute
  '/agents/providers/connect': typeof AuthedAgentsProvidersConnectRoute
  '/jobs/runs/$id': typeof AuthedJobsRunsIdRoute
  '/providers/$id/edit': typeof AuthedProvidersIdEditRoute
  '/targets/$id/$tab': typeof AuthedTargetsIdTabRoute
  '/agents/$id': typeof AuthedAgentsIdIndexRoute
  '/agents/conversations': typeof AuthedAgentsConversationsIndexRoute
  '/providers/$id': typeof AuthedProvidersIdIndexRoute
  '/targets/$id': typeof AuthedTargetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/init-admin': typeof InitAdminRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/workers': typeof AuthedWorkersRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/_authed/': typeof AuthedIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/agents/create': typeof AuthedAgentsCreateRoute
  '/_authed/assets/$id': typeof AuthedAssetsIdRoute
  '/_authed/groups/$id': typeof AuthedGroupsIdRoute
  '/_authed/internal-networks/$id': typeof AuthedInternalNetworksIdRoute
  '/_authed/internal-networks/create': typeof AuthedInternalNetworksCreateRoute
  '/_authed/issues/$id': typeof AuthedIssuesIdRoute
  '/_authed/issues/create': typeof AuthedIssuesCreateRoute
  '/_authed/providers/create': typeof AuthedProvidersCreateRoute
  '/_authed/targets/start-discovery': typeof AuthedTargetsStartDiscoveryRoute
  '/_authed/tools/$id': typeof AuthedToolsIdRoute
  '/_authed/vulnerabilities/$id': typeof AuthedVulnerabilitiesIdRoute
  '/_authed/workspaces/create': typeof AuthedWorkspacesCreateRoute
  '/_authed/agents/': typeof AuthedAgentsIndexRoute
  '/_authed/assets/': typeof AuthedAssetsIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/internal-networks/': typeof AuthedInternalNetworksIndexRoute
  '/_authed/issues/': typeof AuthedIssuesIndexRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/providers/': typeof AuthedProvidersIndexRoute
  '/_authed/targets/': typeof AuthedTargetsIndexRoute
  '/_authed/tools/': typeof AuthedToolsIndexRoute
  '/_authed/vulnerabilities/': typeof AuthedVulnerabilitiesIndexRoute
  '/_authed/workspaces/': typeof AuthedWorkspacesIndexRoute
  '/_authed/agents/$id/edit': typeof AuthedAgentsIdEditRoute
  '/_authed/agents/conversations/$conversationId': typeof AuthedAgentsConversationsConversationIdRoute
  '/_authed/agents/providers/connect': typeof AuthedAgentsProvidersConnectRoute
  '/_authed/jobs/runs/$id': typeof AuthedJobsRunsIdRoute
  '/_authed/providers/$id/edit': typeof AuthedProvidersIdEditRoute
  '/_authed/targets/$id/$tab': typeof AuthedTargetsIdTabRoute
  '/_authed/agents/$id/': typeof AuthedAgentsIdIndexRoute
  '/_authed/agents/conversations/': typeof AuthedAgentsConversationsIndexRoute
  '/_authed/providers/$id/': typeof AuthedProvidersIdIndexRoute
  '/_authed/targets/$id/': typeof AuthedTargetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/init-admin'
    | '/login'
    | '/settings'
    | '/notifications'
    | '/reports'
    | '/search'
    | '/workers'
    | '/settings/$tab'
    | '/settings/'
    | '/admin/users'
    | '/agents/create'
    | '/assets/$id'
    | '/groups/$id'
    | '/internal-networks/$id'
    | '/internal-networks/create'
    | '/issues/$id'
    | '/issues/create'
    | '/providers/create'
    | '/targets/start-discovery'
    | '/tools/$id'
    | '/vulnerabilities/$id'
    | '/workspaces/create'
    | '/agents/'
    | '/assets/'
    | '/groups/'
    | '/internal-networks/'
    | '/issues/'
    | '/jobs/'
    | '/providers/'
    | '/targets/'
    | '/tools/'
    | '/vulnerabilities/'
    | '/workspaces/'
    | '/agents/$id/edit'
    | '/agents/conversations/$conversationId'
    | '/agents/providers/connect'
    | '/jobs/runs/$id'
    | '/providers/$id/edit'
    | '/targets/$id/$tab'
    | '/agents/$id/'
    | '/agents/conversations/'
    | '/providers/$id/'
    | '/targets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/init-admin'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/search'
    | '/workers'
    | '/settings/$tab'
    | '/'
    | '/settings'
    | '/admin/users'
    | '/agents/create'
    | '/assets/$id'
    | '/groups/$id'
    | '/internal-networks/$id'
    | '/internal-networks/create'
    | '/issues/$id'
    | '/issues/create'
    | '/providers/create'
    | '/targets/start-discovery'
    | '/tools/$id'
    | '/vulnerabilities/$id'
    | '/workspaces/create'
    | '/agents'
    | '/assets'
    | '/groups'
    | '/internal-networks'
    | '/issues'
    | '/jobs'
    | '/providers'
    | '/targets'
    | '/tools'
    | '/vulnerabilities'
    | '/workspaces'
    | '/agents/$id/edit'
    | '/agents/conversations/$conversationId'
    | '/agents/providers/connect'
    | '/jobs/runs/$id'
    | '/providers/$id/edit'
    | '/targets/$id/$tab'
    | '/agents/$id'
    | '/agents/conversations'
    | '/providers/$id'
    | '/targets/$id'
  id:
    | '__root__'
    | '/$'
    | '/_authed'
    | '/init-admin'
    | '/login'
    | '/settings'
    | '/_authed/notifications'
    | '/_authed/reports'
    | '/_authed/search'
    | '/_authed/workers'
    | '/settings/$tab'
    | '/_authed/'
    | '/settings/'
    | '/_authed/admin/users'
    | '/_authed/agents/create'
    | '/_authed/assets/$id'
    | '/_authed/groups/$id'
    | '/_authed/internal-networks/$id'
    | '/_authed/internal-networks/create'
    | '/_authed/issues/$id'
    | '/_authed/issues/create'
    | '/_authed/providers/create'
    | '/_authed/targets/start-discovery'
    | '/_authed/tools/$id'
    | '/_authed/vulnerabilities/$id'
    | '/_authed/workspaces/create'
    | '/_authed/agents/'
    | '/_authed/assets/'
    | '/_authed/groups/'
    | '/_authed/internal-networks/'
    | '/_authed/issues/'
    | '/_authed/jobs/'
    | '/_authed/providers/'
    | '/_authed/targets/'
    | '/_authed/tools/'
    | '/_authed/vulnerabilities/'
    | '/_authed/workspaces/'
    | '/_authed/agents/$id/edit'
    | '/_authed/agents/conversations/$conversationId'
    | '/_authed/agents/providers/connect'
    | '/_authed/jobs/runs/$id'
    | '/_authed/providers/$id/edit'
    | '/_authed/targets/$id/$tab'
    | '/_authed/agents/$id/'
    | '/_authed/agents/conversations/'
    | '/_authed/providers/$id/'
    | '/_authed/targets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  InitAdminRoute: typeof InitAdminRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init-admin': {
      id: '/init-admin'
      path: '/init-admin'
      fullPath: '/init-admin'
      preLoaderRoute: typeof InitAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/settings/$tab': {
      id: '/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof SettingsTabRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authed/workers': {
      id: '/_authed/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthedWorkersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workspaces/': {
      id: '/_authed/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthedWorkspacesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vulnerabilities/': {
      id: '/_authed/vulnerabilities/'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities/'
      preLoaderRoute: typeof AuthedVulnerabilitiesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tools/': {
      id: '/_authed/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthedToolsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/targets/': {
      id: '/_authed/targets/'
      path: '/targets'
      fullPath: '/targets/'
      preLoaderRoute: typeof AuthedTargetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/providers/': {
      id: '/_authed/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthedProvidersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/issues/': {
      id: '/_authed/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthedIssuesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/internal-networks/': {
      id: '/_authed/internal-networks/'
      path: '/internal-networks'
      fullPath: '/internal-networks/'
      preLoaderRoute: typeof AuthedInternalNetworksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/': {
      id: '/_authed/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthedAssetsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/': {
      id: '/_authed/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAgentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workspaces/create': {
      id: '/_authed/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AuthedWorkspacesCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vulnerabilities/$id': {
      id: '/_authed/vulnerabilities/$id'
      path: '/vulnerabilities/$id'
      fullPath: '/vulnerabilities/$id'
      preLoaderRoute: typeof AuthedVulnerabilitiesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tools/$id': {
      id: '/_authed/tools/$id'
      path: '/tools/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof AuthedToolsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/targets/start-discovery': {
      id: '/_authed/targets/start-discovery'
      path: '/targets/start-discovery'
      fullPath: '/targets/start-discovery'
      preLoaderRoute: typeof AuthedTargetsStartDiscoveryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/providers/create': {
      id: '/_authed/providers/create'
      path: '/providers/create'
      fullPath: '/providers/create'
      preLoaderRoute: typeof AuthedProvidersCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/issues/create': {
      id: '/_authed/issues/create'
      path: '/issues/create'
      fullPath: '/issues/create'
      preLoaderRoute: typeof AuthedIssuesCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/issues/$id': {
      id: '/_authed/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthedIssuesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/internal-networks/create': {
      id: '/_authed/internal-networks/create'
      path: '/internal-networks/create'
      fullPath: '/internal-networks/create'
      preLoaderRoute: typeof AuthedInternalNetworksCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/internal-networks/$id': {
      id: '/_authed/internal-networks/$id'
      path: '/internal-networks/$id'
      fullPath: '/internal-networks/$id'
      preLoaderRoute: typeof AuthedInternalNetworksIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id': {
      id: '/_authed/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthedGroupsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assets/$id': {
      id: '/_authed/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthedAssetsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/create': {
      id: '/_authed/agents/create'
      path: '/agents/create'
      fullPath: '/agents/create'
      preLoaderRoute: typeof AuthedAgentsCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/targets/$id/': {
      id: '/_authed/targets/$id/'
      path: '/targets/$id'
      fullPath: '/targets/$id/'
      preLoaderRoute: typeof AuthedTargetsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/providers/$id/': {
      id: '/_authed/providers/$id/'
      path: '/providers/$id'
      fullPath: '/providers/$id/'
      preLoaderRoute: typeof AuthedProvidersIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/conversations/': {
      id: '/_authed/agents/conversations/'
      path: '/agents/conversations'
      fullPath: '/agents/conversations/'
      preLoaderRoute: typeof AuthedAgentsConversationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$id/': {
      id: '/_authed/agents/$id/'
      path: '/agents/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AuthedAgentsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/targets/$id/$tab': {
      id: '/_authed/targets/$id/$tab'
      path: '/targets/$id/$tab'
      fullPath: '/targets/$id/$tab'
      preLoaderRoute: typeof AuthedTargetsIdTabRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/providers/$id/edit': {
      id: '/_authed/providers/$id/edit'
      path: '/providers/$id/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof AuthedProvidersIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/runs/$id': {
      id: '/_authed/jobs/runs/$id'
      path: '/jobs/runs/$id'
      fullPath: '/jobs/runs/$id'
      preLoaderRoute: typeof AuthedJobsRunsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/providers/connect': {
      id: '/_authed/agents/providers/connect'
      path: '/agents/providers/connect'
      fullPath: '/agents/providers/connect'
      preLoaderRoute: typeof AuthedAgentsProvidersConnectRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/conversations/$conversationId': {
      id: '/_authed/agents/conversations/$conversationId'
      path: '/agents/conversations/$conversationId'
      fullPath: '/agents/conversations/$conversationId'
      preLoaderRoute: typeof AuthedAgentsConversationsConversationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$id/edit': {
      id: '/_authed/agents/$id/edit'
      path: '/agents/$id/edit'
      fullPath: '/agents/$id/edit'
      preLoaderRoute: typeof AuthedAgentsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedWorkersRoute: typeof AuthedWorkersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAgentsCreateRoute: typeof AuthedAgentsCreateRoute
  AuthedAssetsIdRoute: typeof AuthedAssetsIdRoute
  AuthedGroupsIdRoute: typeof AuthedGroupsIdRoute
  AuthedInternalNetworksIdRoute: typeof AuthedInternalNetworksIdRoute
  AuthedInternalNetworksCreateRoute: typeof AuthedInternalNetworksCreateRoute
  AuthedIssuesIdRoute: typeof AuthedIssuesIdRoute
  AuthedIssuesCreateRoute: typeof AuthedIssuesCreateRoute
  AuthedProvidersCreateRoute: typeof AuthedProvidersCreateRoute
  AuthedTargetsStartDiscoveryRoute: typeof AuthedTargetsStartDiscoveryRoute
  AuthedToolsIdRoute: typeof AuthedToolsIdRoute
  AuthedVulnerabilitiesIdRoute: typeof AuthedVulnerabilitiesIdRoute
  AuthedWorkspacesCreateRoute: typeof AuthedWorkspacesCreateRoute
  AuthedAgentsIndexRoute: typeof AuthedAgentsIndexRoute
  AuthedAssetsIndexRoute: typeof AuthedAssetsIndexRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedInternalNetworksIndexRoute: typeof AuthedInternalNetworksIndexRoute
  AuthedIssuesIndexRoute: typeof AuthedIssuesIndexRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
  AuthedProvidersIndexRoute: typeof AuthedProvidersIndexRoute
  AuthedTargetsIndexRoute: typeof AuthedTargetsIndexRoute
  AuthedToolsIndexRoute: typeof AuthedToolsIndexRoute
  AuthedVulnerabilitiesIndexRoute: typeof AuthedVulnerabilitiesIndexRoute
  AuthedWorkspacesIndexRoute: typeof AuthedWorkspacesIndexRoute
  AuthedAgentsIdEditRoute: typeof AuthedAgentsIdEditRoute
  AuthedAgentsConversationsConversationIdRoute: typeof AuthedAgentsConversationsConversationIdRoute
  AuthedAgentsProvidersConnectRoute: typeof AuthedAgentsProvidersConnectRoute
  AuthedJobsRunsIdRoute: typeof AuthedJobsRunsIdRoute
  AuthedProvidersIdEditRoute: typeof AuthedProvidersIdEditRoute
  AuthedTargetsIdTabRoute: typeof AuthedTargetsIdTabRoute
  AuthedAgentsIdIndexRoute: typeof AuthedAgentsIdIndexRoute
  AuthedAgentsConversationsIndexRoute: typeof AuthedAgentsConversationsIndexRoute
  AuthedProvidersIdIndexRoute: typeof AuthedProvidersIdIndexRoute
  AuthedTargetsIdIndexRoute: typeof AuthedTargetsIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedWorkersRoute: AuthedWorkersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAgentsCreateRoute: AuthedAgentsCreateRoute,
  AuthedAssetsIdRoute: AuthedAssetsIdRoute,
  AuthedGroupsIdRoute: AuthedGroupsIdRoute,
  AuthedInternalNetworksIdRoute: AuthedInternalNetworksIdRoute,
  AuthedInternalNetworksCreateRoute: AuthedInternalNetworksCreateRoute,
  AuthedIssuesIdRoute: AuthedIssuesIdRoute,
  AuthedIssuesCreateRoute: AuthedIssuesCreateRoute,
  AuthedProvidersCreateRoute: AuthedProvidersCreateRoute,
  AuthedTargetsStartDiscoveryRoute: AuthedTargetsStartDiscoveryRoute,
  AuthedToolsIdRoute: AuthedToolsIdRoute,
  AuthedVulnerabilitiesIdRoute: AuthedVulnerabilitiesIdRoute,
  AuthedWorkspacesCreateRoute: AuthedWorkspacesCreateRoute,
  AuthedAgentsIndexRoute: AuthedAgentsIndexRoute,
  AuthedAssetsIndexRoute: AuthedAssetsIndexRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedInternalNetworksIndexRoute: AuthedInternalNetworksIndexRoute,
  AuthedIssuesIndexRoute: AuthedIssuesIndexRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
  AuthedProvidersIndexRoute: AuthedProvidersIndexRoute,
  AuthedTargetsIndexRoute: AuthedTargetsIndexRoute,
  AuthedToolsIndexRoute: AuthedToolsIndexRoute,
  AuthedVulnerabilitiesIndexRoute: AuthedVulnerabilitiesIndexRoute,
  AuthedWorkspacesIndexRoute: AuthedWorkspacesIndexRoute,
  AuthedAgentsIdEditRoute: AuthedAgentsIdEditRoute,
  AuthedAgentsConversationsConversationIdRoute:
    AuthedAgentsConversationsConversationIdRoute,
  AuthedAgentsProvidersConnectRoute: AuthedAgentsProvidersConnectRoute,
  AuthedJobsRunsIdRoute: AuthedJobsRunsIdRoute,
  AuthedProvidersIdEditRoute: AuthedProvidersIdEditRoute,
  AuthedTargetsIdTabRoute: AuthedTargetsIdTabRoute,
  AuthedAgentsIdIndexRoute: AuthedAgentsIdIndexRoute,
  AuthedAgentsConversationsIndexRoute: AuthedAgentsConversationsIndexRoute,
  AuthedProvidersIdIndexRoute: AuthedProvidersIdIndexRoute,
  AuthedTargetsIdIndexRoute: AuthedTargetsIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SettingsRouteChildren {
  SettingsTabRoute: typeof SettingsTabRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsTabRoute: SettingsTabRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  InitAdminRoute: InitAdminRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
